"""Curated worldwide seed catalog for the source registry.

``SEED_SOURCES`` is a large, hand-curated list of real news/feed sources spanning
every region, many languages, and all domains — general, economy/markets/finance,
business, technology, **science** (arXiv, Nature, EurekAlert, phys.org, …), and
**niche/long-tail** specialist outlets. Coverage is intentionally boundary-less.

Each entry is a plain dict with the keys consumed by
:class:`newskoo.sources.schemas.SourceCreate`:

    name, homepage_url, feed_url, api_kind, fetch_method, region,
    languages, categories, bot_sensitivity

``feed_url`` holds a real RSS/Atom URL where one exists; otherwise it is ``None``
and ``fetch_method`` is ``"html"`` (or ``"api"`` for GDELT/NewsAPI-style
sources). A handful of URLs are approximate and flagged in the module docstring
of the project summary — breadth matters more than per-URL exactness here.

:func:`seed_sources` upserts every entry idempotently via
:func:`newskoo.sources.registry.upsert_source`.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from newskoo.core.logging import get_logger
from newskoo.sources.registry import upsert_source
from newskoo.sources.schemas import SourceCreate

log = get_logger(__name__)


def _s(
    name: str,
    homepage_url: str,
    feed_url: str | None,
    region: str,
    languages: list[str],
    categories: list[str],
    *,
    fetch_method: str | None = None,
    api_kind: str | None = None,
    bot_sensitivity: int = 0,
) -> dict[str, Any]:
    """Compact constructor; defaults fetch_method to rss/html based on feed_url."""
    if fetch_method is None:
        fetch_method = "api" if api_kind else ("rss" if feed_url else "html")
    return {
        "name": name,
        "homepage_url": homepage_url,
        "feed_url": feed_url,
        "api_kind": api_kind,
        "fetch_method": fetch_method,
        "region": region,
        "languages": languages,
        "categories": categories,
        "bot_sensitivity": bot_sensitivity,
    }


SEED_SOURCES: list[dict[str, Any]] = [
    # ── Global APIs / aggregators ────────────────────────────────────────────
    _s("GDELT Global Knowledge Graph", "https://www.gdeltproject.org/", None,
       "GLOBAL", ["en"], ["general", "world", "politics"], api_kind="gdelt"),
    _s("NewsAPI Top Headlines", "https://newsapi.org/", None,
       "GLOBAL", ["en"], ["general", "world"], api_kind="newsapi"),

    # ── North America: United States ─────────────────────────────────────────
    _s("Associated Press — Top News", "https://apnews.com/", "https://feedx.net/rss/ap.xml",
       "US", ["en"], ["general", "world", "politics"]),
    _s("Reuters — World", "https://www.reuters.com/", "https://feeds.reuters.com/Reuters/worldNews",
       "US", ["en"], ["general", "world", "business"], bot_sensitivity=1),
    _s("Reuters — Business", "https://www.reuters.com/business/",
       "https://feeds.reuters.com/reuters/businessNews",
       "US", ["en"], ["business", "economy", "markets"], bot_sensitivity=1),
    _s("The New York Times — World", "https://www.nytimes.com/",
       "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
       "US", ["en"], ["general", "world", "politics"], bot_sensitivity=1),
    _s("The New York Times — Business", "https://www.nytimes.com/section/business",
       "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
       "US", ["en"], ["business", "economy"], bot_sensitivity=1),
    _s("The New York Times — Technology", "https://www.nytimes.com/section/technology",
       "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
       "US", ["en"], ["technology"], bot_sensitivity=1),
    _s("The New York Times — Science", "https://www.nytimes.com/section/science",
       "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
       "US", ["en"], ["science"], bot_sensitivity=1),
    _s("The Washington Post — World", "https://www.washingtonpost.com/world/",
       "https://feeds.washingtonpost.com/rss/world",
       "US", ["en"], ["general", "world", "politics"], bot_sensitivity=2),
    _s("The Wall Street Journal — Markets", "https://www.wsj.com/",
       "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
       "US", ["en"], ["markets", "finance", "economy"], bot_sensitivity=2),
    _s("The Wall Street Journal — World", "https://www.wsj.com/news/world",
       "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
       "US", ["en"], ["world", "general"], bot_sensitivity=2),
    _s("CNBC — Top News", "https://www.cnbc.com/", "https://www.cnbc.com/id/100003114/device/rss/rss.html",
       "US", ["en"], ["business", "markets", "finance"]),
    _s("CNBC — Technology", "https://www.cnbc.com/technology/",
       "https://www.cnbc.com/id/19854910/device/rss/rss.html",
       "US", ["en"], ["technology", "business"]),
    _s("Bloomberg — Markets", "https://www.bloomberg.com/markets",
       "https://feeds.bloomberg.com/markets/news.rss",
       "US", ["en"], ["markets", "finance", "economy"], bot_sensitivity=3),
    _s("Bloomberg — Technology", "https://www.bloomberg.com/technology",
       "https://feeds.bloomberg.com/technology/news.rss",
       "US", ["en"], ["technology", "business"], bot_sensitivity=3),
    _s("CNN — Top Stories", "https://www.cnn.com/", "http://rss.cnn.com/rss/edition.rss",
       "US", ["en"], ["general", "world"]),
    _s("CNN — Money", "https://www.cnn.com/business", "http://rss.cnn.com/rss/money_latest.rss",
       "US", ["en"], ["business", "economy"]),
    _s("NPR — News", "https://www.npr.org/", "https://feeds.npr.org/1001/rss.xml",
       "US", ["en"], ["general", "world", "politics"]),
    _s("NPR — Science", "https://www.npr.org/sections/science/",
       "https://feeds.npr.org/1007/rss.xml",
       "US", ["en"], ["science"]),
    _s("USA Today", "https://www.usatoday.com/", "https://rssfeeds.usatoday.com/usatoday-NewsTopStories",
       "US", ["en"], ["general", "world"]),
    _s("Los Angeles Times", "https://www.latimes.com/", "https://www.latimes.com/local/rss2.0.xml",
       "US", ["en"], ["general", "world"], bot_sensitivity=1),
    _s("Politico", "https://www.politico.com/", "https://www.politico.com/rss/politicopicks.xml",
       "US", ["en"], ["politics", "general"]),
    _s("The Hill", "https://thehill.com/", "https://thehill.com/news/feed/",
       "US", ["en"], ["politics", "general"]),
    _s("MarketWatch — Top Stories", "https://www.marketwatch.com/",
       "https://feeds.content.dowjones.io/public/rss/mw_topstories",
       "US", ["en"], ["markets", "finance", "economy"], bot_sensitivity=1),
    _s("Yahoo Finance", "https://finance.yahoo.com/", "https://finance.yahoo.com/news/rssindex",
       "US", ["en"], ["markets", "finance", "business"]),
    _s("Forbes — Business", "https://www.forbes.com/business/", "https://www.forbes.com/business/feed/",
       "US", ["en"], ["business", "economy"], bot_sensitivity=1),
    _s("Fortune", "https://fortune.com/", "https://fortune.com/feed/",
       "US", ["en"], ["business", "economy"]),
    _s("Business Insider", "https://www.businessinsider.com/",
       "https://www.businessinsider.com/rss",
       "US", ["en"], ["business", "technology", "finance"], bot_sensitivity=1),
    _s("TechCrunch", "https://techcrunch.com/", "https://techcrunch.com/feed/",
       "US", ["en"], ["technology", "business"]),
    _s("The Verge", "https://www.theverge.com/", "https://www.theverge.com/rss/index.xml",
       "US", ["en"], ["technology"]),
    _s("Wired", "https://www.wired.com/", "https://www.wired.com/feed/rss",
       "US", ["en"], ["technology", "science"], bot_sensitivity=1),
    _s("Ars Technica", "https://arstechnica.com/", "https://feeds.arstechnica.com/arstechnica/index",
       "US", ["en"], ["technology", "science"]),
    _s("Engadget", "https://www.engadget.com/", "https://www.engadget.com/rss.xml",
       "US", ["en"], ["technology"]),
    _s("Hacker News (front page)", "https://news.ycombinator.com/", "https://hnrss.org/frontpage",
       "US", ["en"], ["technology", "startups"]),
    _s("MIT Technology Review", "https://www.technologyreview.com/",
       "https://www.technologyreview.com/feed/",
       "US", ["en"], ["technology", "science"], bot_sensitivity=1),
    _s("VentureBeat", "https://venturebeat.com/", "https://venturebeat.com/feed/",
       "US", ["en"], ["technology", "business", "startups"]),
    _s("The Information", "https://www.theinformation.com/", None,
       "US", ["en"], ["technology", "business"], bot_sensitivity=2),
    _s("Axios", "https://www.axios.com/", "https://api.axios.com/feed/",
       "US", ["en"], ["general", "business", "politics"]),
    _s("ProPublica", "https://www.propublica.org/", "https://www.propublica.org/feeds/propublica/main",
       "US", ["en"], ["investigative", "politics", "niche"]),
    _s("Federal Reserve — Press Releases", "https://www.federalreserve.gov/",
       "https://www.federalreserve.gov/feeds/press_all.xml",
       "US", ["en"], ["economy", "finance", "policy", "niche"]),
    _s("SEC — Press Releases", "https://www.sec.gov/", "https://www.sec.gov/news/pressreleases.rss",
       "US", ["en"], ["finance", "regulation", "niche"]),

    # ── North America: Canada ────────────────────────────────────────────────
    _s("CBC News — Top Stories", "https://www.cbc.ca/news",
       "https://www.cbc.ca/webfeed/rss/rss-topstories",
       "CA", ["en"], ["general", "world"]),
    _s("The Globe and Mail", "https://www.theglobeandmail.com/",
       "https://www.theglobeandmail.com/feed/",
       "CA", ["en"], ["general", "business"], bot_sensitivity=1),
    _s("Financial Post", "https://financialpost.com/", "https://financialpost.com/feed/",
       "CA", ["en"], ["business", "economy", "markets"]),
    _s("Radio-Canada", "https://ici.radio-canada.ca/", "https://ici.radio-canada.ca/rss/4159",
       "CA", ["fr"], ["general", "world"]),

    # ── North America: Mexico (also Latin America bridge) ────────────────────
    _s("El Universal (Mexico)", "https://www.eluniversal.com.mx/",
       "https://www.eluniversal.com.mx/rss.xml",
       "MX", ["es"], ["general", "world"]),
    _s("Milenio", "https://www.milenio.com/", "https://www.milenio.com/rss",
       "MX", ["es"], ["general", "business"]),

    # ── UK / Ireland ─────────────────────────────────────────────────────────
    _s("BBC News — Top Stories", "https://www.bbc.com/news", "http://feeds.bbci.co.uk/news/rss.xml",
       "GB", ["en"], ["general", "world"]),
    _s("BBC News — Business", "https://www.bbc.com/news/business",
       "http://feeds.bbci.co.uk/news/business/rss.xml",
       "GB", ["en"], ["business", "economy"]),
    _s("BBC News — Technology", "https://www.bbc.com/news/technology",
       "http://feeds.bbci.co.uk/news/technology/rss.xml",
       "GB", ["en"], ["technology"]),
    _s("BBC News — Science & Environment", "https://www.bbc.com/news/science_and_environment",
       "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
       "GB", ["en"], ["science", "environment"]),
    _s("The Guardian — World", "https://www.theguardian.com/world",
       "https://www.theguardian.com/world/rss",
       "GB", ["en"], ["general", "world", "politics"]),
    _s("The Guardian — Business", "https://www.theguardian.com/uk/business",
       "https://www.theguardian.com/uk/business/rss",
       "GB", ["en"], ["business", "economy"]),
    _s("The Guardian — Technology", "https://www.theguardian.com/uk/technology",
       "https://www.theguardian.com/uk/technology/rss",
       "GB", ["en"], ["technology"]),
    _s("The Guardian — Science", "https://www.theguardian.com/science",
       "https://www.theguardian.com/science/rss",
       "GB", ["en"], ["science"]),
    _s("Financial Times — Home", "https://www.ft.com/", "https://www.ft.com/rss/home",
       "GB", ["en"], ["business", "economy", "markets", "finance"], bot_sensitivity=2),
    _s("The Economist", "https://www.economist.com/", "https://www.economist.com/finance-and-economics/rss.xml",
       "GB", ["en"], ["economy", "finance", "world"], bot_sensitivity=2),
    _s("The Telegraph", "https://www.telegraph.co.uk/", "https://www.telegraph.co.uk/news/rss.xml",
       "GB", ["en"], ["general", "world", "politics"], bot_sensitivity=1),
    _s("The Independent", "https://www.independent.co.uk/", "https://www.independent.co.uk/news/rss",
       "GB", ["en"], ["general", "world"]),
    _s("Sky News", "https://news.sky.com/", "https://feeds.skynews.com/feeds/rss/home.xml",
       "GB", ["en"], ["general", "world"]),
    _s("The Register (tech)", "https://www.theregister.com/", "https://www.theregister.com/headlines.atom",
       "GB", ["en"], ["technology", "niche"]),
    _s("Nature (journal)", "https://www.nature.com/", "https://www.nature.com/nature.rss",
       "GB", ["en"], ["science", "research"]),
    _s("New Scientist", "https://www.newscientist.com/", "https://www.newscientist.com/feed/home/",
       "GB", ["en"], ["science"], bot_sensitivity=1),
    _s("RTÉ News (Ireland)", "https://www.rte.ie/news/", "https://www.rte.ie/feeds/rss/?index=/news/",
       "IE", ["en"], ["general", "world"]),
    _s("The Irish Times", "https://www.irishtimes.com/", "https://www.irishtimes.com/cmlink/news-1.1319192",
       "IE", ["en"], ["general", "world"]),

    # ── Western Europe ───────────────────────────────────────────────────────
    _s("Le Monde", "https://www.lemonde.fr/", "https://www.lemonde.fr/rss/une.xml",
       "FR", ["fr"], ["general", "world", "politics"], bot_sensitivity=1),
    _s("Le Figaro", "https://www.lefigaro.fr/", "https://www.lefigaro.fr/rss/figaro_actualites.xml",
       "FR", ["fr"], ["general", "world"]),
    _s("Libération", "https://www.liberation.fr/", "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml",
       "FR", ["fr"], ["general", "politics"]),
    _s("France 24 (français)", "https://www.france24.com/fr/",
       "https://www.france24.com/fr/rss",
       "FR", ["fr"], ["general", "world"]),
    _s("Les Échos", "https://www.lesechos.fr/", "https://www.lesechos.fr/rss/rss_une_titres.xml",
       "FR", ["fr"], ["business", "economy", "markets"], bot_sensitivity=1),
    _s("Der Spiegel", "https://www.spiegel.de/", "https://www.spiegel.de/schlagzeilen/index.rss",
       "DE", ["de"], ["general", "world", "politics"]),
    _s("Die Zeit", "https://www.zeit.de/", "https://newsfeed.zeit.de/index",
       "DE", ["de"], ["general", "politics"], bot_sensitivity=1),
    _s("Frankfurter Allgemeine (FAZ)", "https://www.faz.net/", "https://www.faz.net/rss/aktuell/",
       "DE", ["de"], ["general", "business", "economy"]),
    _s("Süddeutsche Zeitung", "https://www.sueddeutsche.de/", "https://rss.sueddeutsche.de/rss/Topthemen",
       "DE", ["de"], ["general", "politics"], bot_sensitivity=1),
    _s("Handelsblatt", "https://www.handelsblatt.com/", "https://www.handelsblatt.com/contentexport/feed/schlagzeilen",
       "DE", ["de"], ["business", "economy", "markets"], bot_sensitivity=1),
    _s("Deutsche Welle (Deutsch)", "https://www.dw.com/de/", "https://rss.dw.com/rdf/rss-de-all",
       "DE", ["de"], ["general", "world"]),
    _s("Deutsche Welle (English)", "https://www.dw.com/en/", "https://rss.dw.com/rdf/rss-en-all",
       "DE", ["en"], ["general", "world"]),
    _s("Heise Online (tech, DE)", "https://www.heise.de/", "https://www.heise.de/rss/heise-atom.xml",
       "DE", ["de"], ["technology", "niche"]),
    _s("El País", "https://elpais.com/", "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
       "ES", ["es"], ["general", "world", "politics"], bot_sensitivity=1),
    _s("El Mundo", "https://www.elmundo.es/", "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
       "ES", ["es"], ["general", "world"]),
    _s("La Vanguardia", "https://www.lavanguardia.com/", "https://www.lavanguardia.com/rss/home.xml",
       "ES", ["es"], ["general", "world"]),
    _s("Expansión (ES economía)", "https://www.expansion.com/", "https://e00-expansion.uecdn.es/rss/portada.xml",
       "ES", ["es"], ["economy", "markets", "business"]),
    _s("Corriere della Sera", "https://www.corriere.it/", "https://xml2.corriereobjects.it/rss/homepage.xml",
       "IT", ["it"], ["general", "world"]),
    _s("La Repubblica", "https://www.repubblica.it/", "https://www.repubblica.it/rss/homepage/rss2.0.xml",
       "IT", ["it"], ["general", "politics"]),
    _s("Il Sole 24 Ore", "https://www.ilsole24ore.com/", "https://www.ilsole24ore.com/rss/economia.xml",
       "IT", ["it"], ["economy", "markets", "finance"]),
    _s("ANSA (Italy)", "https://www.ansa.it/", "https://www.ansa.it/sito/ansait_rss.xml",
       "IT", ["it"], ["general", "world"]),
    _s("NOS (Netherlands)", "https://nos.nl/", "https://feeds.nos.nl/nosnieuwsalgemeen",
       "NL", ["nl"], ["general", "world"]),
    _s("de Volkskrant", "https://www.volkskrant.nl/", "https://www.volkskrant.nl/voorpagina/rss.xml",
       "NL", ["nl"], ["general", "politics"], bot_sensitivity=1),
    _s("RTBF (Belgium, FR)", "https://www.rtbf.be/", "https://www.rtbf.be/site-rss/rss",
       "BE", ["fr"], ["general", "world"]),
    _s("Swissinfo (CH)", "https://www.swissinfo.ch/", "https://www.swissinfo.ch/eng/rss",
       "CH", ["en", "de", "fr"], ["general", "world", "business"]),
    _s("Neue Zürcher Zeitung (NZZ)", "https://www.nzz.ch/", "https://www.nzz.ch/recent.rss",
       "CH", ["de"], ["general", "economy"], bot_sensitivity=1),
    _s("Público (Portugal)", "https://www.publico.pt/", "https://feeds.feedburner.com/PublicoRSS",
       "PT", ["pt"], ["general", "world"]),
    _s("Expresso (Portugal)", "https://expresso.pt/", "https://expresso.pt/rss",
       "PT", ["pt"], ["general", "economy"]),
    _s("Kathimerini (Greece, EN)", "https://www.ekathimerini.com/",
       "https://www.ekathimerini.com/feed/",
       "GR", ["en"], ["general", "world"]),

    # ── Nordics ──────────────────────────────────────────────────────────────
    _s("Yle (Finland, EN)", "https://yle.fi/news", "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS",
       "FI", ["en"], ["general", "world"]),
    _s("Helsingin Sanomat", "https://www.hs.fi/", "https://www.hs.fi/rss/tuoreimmat.xml",
       "FI", ["fi"], ["general", "world"]),
    _s("Svenska Dagbladet (SvD)", "https://www.svd.se/", "https://www.svd.se/feed/articles.rss",
       "SE", ["sv"], ["general", "economy"]),
    _s("Dagens Nyheter (DN)", "https://www.dn.se/", "https://www.dn.se/rss/",
       "SE", ["sv"], ["general", "world"], bot_sensitivity=1),
    _s("Aftenposten (Norway)", "https://www.aftenposten.no/", "https://www.aftenposten.no/rss",
       "NO", ["no"], ["general", "world"]),
    _s("NRK (Norway)", "https://www.nrk.no/", "https://www.nrk.no/toppsaker.rss",
       "NO", ["no"], ["general", "world"]),
    _s("Politiken (Denmark)", "https://politiken.dk/", "https://politiken.dk/rss/senestenyt.rss",
       "DK", ["da"], ["general", "world"]),
    _s("DR (Denmark)", "https://www.dr.dk/nyheder", "https://www.dr.dk/nyheder/service/feeds/allenyheder",
       "DK", ["da"], ["general", "world"]),
    _s("RÚV (Iceland)", "https://www.ruv.is/", "https://www.ruv.is/rss/frettir",
       "IS", ["is"], ["general", "world"]),

    # ── Eastern Europe / Central Europe ──────────────────────────────────────
    _s("Gazeta Wyborcza (Poland)", "https://wyborcza.pl/", "https://wyborcza.pl/pub/rss/wyborcza.xml",
       "PL", ["pl"], ["general", "politics"]),
    _s("TVN24 (Poland)", "https://tvn24.pl/", "https://tvn24.pl/najnowsze.xml",
       "PL", ["pl"], ["general", "world"]),
    _s("iDNES (Czechia)", "https://www.idnes.cz/", "https://servis.idnes.cz/rss.aspx?c=zpravodaj",
       "CZ", ["cs"], ["general", "world"]),
    _s("Index.hu (Hungary)", "https://index.hu/", "https://index.hu/24ora/rss/",
       "HU", ["hu"], ["general", "world"]),
    _s("Kyiv Independent (Ukraine)", "https://kyivindependent.com/",
       "https://kyivindependent.com/feed/",
       "UA", ["en"], ["general", "world", "politics"]),
    _s("Ukrainska Pravda", "https://www.pravda.com.ua/", "https://www.pravda.com.ua/rss/",
       "UA", ["uk"], ["general", "politics"]),
    _s("Hotnews.ro (Romania)", "https://www.hotnews.ro/", "https://www.hotnews.ro/rss",
       "RO", ["ro"], ["general", "world"]),

    # ── Russia ───────────────────────────────────────────────────────────────
    _s("TASS (English)", "https://tass.com/", "https://tass.com/rss/v2.xml",
       "RU", ["en"], ["general", "world", "politics"]),
    _s("RT (English)", "https://www.rt.com/", "https://www.rt.com/rss/",
       "RU", ["en"], ["general", "world", "politics"], bot_sensitivity=1),
    _s("RIA Novosti", "https://ria.ru/", "https://ria.ru/export/rss2/archive/index.xml",
       "RU", ["ru"], ["general", "world"]),
    _s("Meduza (RU independent)", "https://meduza.io/", "https://meduza.io/rss/all",
       "RU", ["ru"], ["general", "politics", "niche"]),

    # ── Middle East ──────────────────────────────────────────────────────────
    _s("Al Jazeera English", "https://www.aljazeera.com/", "https://www.aljazeera.com/xml/rss/all.xml",
       "QA", ["en"], ["general", "world", "politics"]),
    _s("Al Jazeera Arabic", "https://www.aljazeera.net/", "https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9",
       "QA", ["ar"], ["general", "world", "politics"]),
    _s("Al Arabiya (Arabic)", "https://www.alarabiya.net/", "https://www.alarabiya.net/.mrss/ar.xml",
       "AE", ["ar"], ["general", "world"]),
    _s("The Times of Israel", "https://www.timesofisrael.com/", "https://www.timesofisrael.com/feed/",
       "IL", ["en"], ["general", "world", "politics"]),
    _s("Haaretz (English)", "https://www.haaretz.com/", "https://www.haaretz.com/srv/htz---all-articles",
       "IL", ["en"], ["general", "politics"], bot_sensitivity=2),
    _s("Arab News", "https://www.arabnews.com/", "https://www.arabnews.com/rss.xml",
       "SA", ["en"], ["general", "world", "business"]),
    _s("Gulf News (UAE)", "https://gulfnews.com/", "https://gulfnews.com/rss?generatorVersion=1.0",
       "AE", ["en"], ["general", "business", "economy"]),
    _s("The National (UAE)", "https://www.thenationalnews.com/", "https://www.thenationalnews.com/rss",
       "AE", ["en"], ["general", "business"]),
    _s("Daily Sabah (Turkey, EN)", "https://www.dailysabah.com/", "https://www.dailysabah.com/rssFeed/home",
       "TR", ["en"], ["general", "world"]),
    _s("Hürriyet (Turkey)", "https://www.hurriyet.com.tr/", "https://www.hurriyet.com.tr/rss/anasayfa",
       "TR", ["tr"], ["general", "world"]),
    _s("Tehran Times (Iran, EN)", "https://www.tehrantimes.com/", "https://www.tehrantimes.com/rss",
       "IR", ["en"], ["general", "world"]),

    # ── Africa ───────────────────────────────────────────────────────────────
    _s("AllAfrica", "https://allafrica.com/", "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
       "AF", ["en"], ["general", "world"]),
    _s("News24 (South Africa)", "https://www.news24.com/", "https://feeds.24.com/articles/news24/TopStories/rss",
       "ZA", ["en"], ["general", "world"]),
    _s("Daily Maverick (SA)", "https://www.dailymaverick.co.za/", "https://www.dailymaverick.co.za/rss/",
       "ZA", ["en"], ["general", "politics", "business"]),
    _s("Mail & Guardian (SA)", "https://mg.co.za/", "https://mg.co.za/feed/",
       "ZA", ["en"], ["general", "politics"]),
    _s("Premium Times (Nigeria)", "https://www.premiumtimesng.com/", "https://www.premiumtimesng.com/feed",
       "NG", ["en"], ["general", "politics"]),
    _s("The Punch (Nigeria)", "https://punchng.com/", "https://punchng.com/feed/",
       "NG", ["en"], ["general", "business"]),
    _s("Daily Nation (Kenya)", "https://nation.africa/kenya", "https://nation.africa/kenya/rss.xml",
       "KE", ["en"], ["general", "world"]),
    _s("The East African", "https://www.theeastafrican.co.ke/", "https://www.theeastafrican.co.ke/rss.xml",
       "KE", ["en"], ["general", "business", "world"]),
    _s("Ahram Online (Egypt)", "https://english.ahram.org.eg/", "https://english.ahram.org.eg/rss/portal.aspx",
       "EG", ["en"], ["general", "world"]),
    _s("GhanaWeb", "https://www.ghanaweb.com/", "https://www.ghanaweb.com/GhanaHomePage/rss/news.xml",
       "GH", ["en"], ["general", "world"]),
    _s("The Herald (Zimbabwe)", "https://www.herald.co.zw/", "https://www.herald.co.zw/feed/",
       "ZW", ["en"], ["general", "world"]),

    # ── South Asia ───────────────────────────────────────────────────────────
    _s("The Times of India", "https://timesofindia.indiatimes.com/",
       "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
       "IN", ["en"], ["general", "world"]),
    _s("The Hindu", "https://www.thehindu.com/", "https://www.thehindu.com/news/national/feeder/default.rss",
       "IN", ["en"], ["general", "politics"]),
    _s("Hindustan Times", "https://www.hindustantimes.com/", "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml",
       "IN", ["en"], ["general", "world"]),
    _s("Economic Times (India)", "https://economictimes.indiatimes.com/",
       "https://economictimes.indiatimes.com/rssfeedstopstories.cms",
       "IN", ["en"], ["economy", "markets", "business"]),
    _s("Livemint", "https://www.livemint.com/", "https://www.livemint.com/rss/markets",
       "IN", ["en"], ["markets", "finance", "business"]),
    _s("NDTV", "https://www.ndtv.com/", "https://feeds.feedburner.com/ndtvnews-top-stories",
       "IN", ["en"], ["general", "world"]),
    _s("Dawn (Pakistan)", "https://www.dawn.com/", "https://www.dawn.com/feeds/home",
       "PK", ["en"], ["general", "world", "politics"]),
    _s("The Daily Star (Bangladesh)", "https://www.thedailystar.net/", "https://www.thedailystar.net/rss.xml",
       "BD", ["en"], ["general", "world"]),
    _s("The Kathmandu Post (Nepal)", "https://kathmandupost.com/", "https://kathmandupost.com/rss",
       "NP", ["en"], ["general", "world"]),

    # ── Southeast Asia ───────────────────────────────────────────────────────
    _s("Channel NewsAsia", "https://www.channelnewsasia.com/",
       "https://www.channelnewsasia.com/rssfeeds/8395986",
       "SG", ["en"], ["general", "world", "business"]),
    _s("The Straits Times (Singapore)", "https://www.straitstimes.com/",
       "https://www.straitstimes.com/news/world/rss.xml",
       "SG", ["en"], ["general", "world"]),
    _s("Bangkok Post", "https://www.bangkokpost.com/", "https://www.bangkokpost.com/rss/data/topstories.xml",
       "TH", ["en"], ["general", "world", "business"]),
    _s("The Jakarta Post", "https://www.thejakartapost.com/", "https://www.thejakartapost.com/feed",
       "ID", ["en"], ["general", "world"]),
    _s("Kompas (Indonesia)", "https://www.kompas.com/", "https://www.kompas.com/getrss/news",
       "ID", ["id"], ["general", "world"]),
    _s("VnExpress (Vietnam, EN)", "https://e.vnexpress.net/", "https://e.vnexpress.net/rss/news.rss",
       "VN", ["en"], ["general", "world"]),
    _s("Philippine Daily Inquirer", "https://www.inquirer.net/", "https://www.inquirer.net/fullfeed",
       "PH", ["en"], ["general", "world"]),
    _s("Rappler (Philippines)", "https://www.rappler.com/", "https://www.rappler.com/feed/",
       "PH", ["en"], ["general", "politics"]),
    _s("Malay Mail (Malaysia)", "https://www.malaymail.com/", "https://www.malaymail.com/feed/rss",
       "MY", ["en"], ["general", "world"]),

    # ── East Asia: Japan ─────────────────────────────────────────────────────
    _s("NHK News (Japanese)", "https://www3.nhk.or.jp/news/", "https://www3.nhk.or.jp/rss/news/cat0.xml",
       "JP", ["ja"], ["general", "world"]),
    _s("NHK World (English)", "https://www3.nhk.or.jp/nhkworld/", "https://www3.nhk.or.jp/nhkworld/en/news/rss/all.xml",
       "JP", ["en"], ["general", "world"]),
    _s("The Asahi Shimbun (English)", "https://www.asahi.com/ajw/", "https://www.asahi.com/rss/asahi/newsheadlines.rdf",
       "JP", ["ja"], ["general", "world"]),
    _s("The Japan Times", "https://www.japantimes.co.jp/", "https://www.japantimes.co.jp/feed/",
       "JP", ["en"], ["general", "world", "business"]),
    _s("Nikkei Asia", "https://asia.nikkei.com/", "https://asia.nikkei.com/rss/feed/nar",
       "JP", ["en"], ["economy", "markets", "business"], bot_sensitivity=1),
    _s("Mainichi Shimbun", "https://mainichi.jp/", "https://mainichi.jp/rss/etc/mainichi-flash.rss",
       "JP", ["ja"], ["general", "world"]),

    # ── East Asia: Korea ─────────────────────────────────────────────────────
    _s("Yonhap News (English)", "https://en.yna.co.kr/", "https://en.yna.co.kr/RSS/news.xml",
       "KR", ["en"], ["general", "world"]),
    _s("Yonhap News (Korean)", "https://www.yna.co.kr/", "https://www.yna.co.kr/rss/news.xml",
       "KR", ["ko"], ["general", "world"]),
    _s("The Korea Herald", "https://www.koreaherald.com/", "https://www.koreaherald.com/rss/020000000000.xml",
       "KR", ["en"], ["general", "business"]),
    _s("The Korea Times", "https://www.koreatimes.co.kr/", "https://www.koreatimes.co.kr/www/rss/nation.xml",
       "KR", ["en"], ["general", "world"]),
    _s("Chosun Ilbo (Korean)", "https://www.chosun.com/", "https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml",
       "KR", ["ko"], ["general", "politics"]),
    _s("Hankyoreh (Korean)", "https://www.hani.co.kr/", "https://www.hani.co.kr/rss/",
       "KR", ["ko"], ["general", "politics"]),
    _s("Maeil Business (MK, Korean)", "https://www.mk.co.kr/", "https://www.mk.co.kr/rss/30000001/",
       "KR", ["ko"], ["economy", "markets", "business"]),

    # ── East Asia: China / Taiwan / Hong Kong ────────────────────────────────
    _s("Xinhua (English)", "https://english.news.cn/", "https://english.news.cn/rss/worldrss.xml",
       "CN", ["en"], ["general", "world"]),
    _s("Global Times (China, EN)", "https://www.globaltimes.cn/", "https://www.globaltimes.cn/rss/outbrain.xml",
       "CN", ["en"], ["general", "world", "politics"]),
    _s("South China Morning Post", "https://www.scmp.com/", "https://www.scmp.com/rss/91/feed",
       "HK", ["en"], ["general", "world", "business"], bot_sensitivity=2),
    _s("Caixin Global (China, EN)", "https://www.caixinglobal.com/", "https://www.caixinglobal.com/feed/",
       "CN", ["en"], ["economy", "markets", "finance"], bot_sensitivity=1),
    _s("Focus Taiwan (CNA, EN)", "https://focustaiwan.tw/", "https://focustaiwan.tw/rss",
       "TW", ["en"], ["general", "world"]),
    _s("Taipei Times", "https://www.taipeitimes.com/", "https://www.taipeitimes.com/xml/index.rss",
       "TW", ["en"], ["general", "world"]),

    # ── Oceania ──────────────────────────────────────────────────────────────
    _s("ABC News (Australia)", "https://www.abc.net.au/news", "https://www.abc.net.au/news/feed/51120/rss.xml",
       "AU", ["en"], ["general", "world"]),
    _s("The Sydney Morning Herald", "https://www.smh.com.au/", "https://www.smh.com.au/rss/feed.xml",
       "AU", ["en"], ["general", "world", "business"], bot_sensitivity=1),
    _s("The Australian Financial Review", "https://www.afr.com/", "https://www.afr.com/rss/feed.xml",
       "AU", ["en"], ["business", "economy", "markets"], bot_sensitivity=1),
    _s("news.com.au", "https://www.news.com.au/", "https://www.news.com.au/content-feeds/latest-news-national/",
       "AU", ["en"], ["general", "world"]),
    _s("The Guardian Australia", "https://www.theguardian.com/au",
       "https://www.theguardian.com/australia-news/rss",
       "AU", ["en"], ["general", "politics"]),
    _s("RNZ (New Zealand)", "https://www.rnz.co.nz/", "https://www.rnz.co.nz/rss/national.xml",
       "NZ", ["en"], ["general", "world"]),
    _s("The New Zealand Herald", "https://www.nzherald.co.nz/", "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/business/?outputType=xml",
       "NZ", ["en"], ["general", "business"]),
    _s("ABC (Pacific Beat)", "https://www.abc.net.au/pacific", "https://www.abc.net.au/news/feed/8204606/rss.xml",
       "AU", ["en"], ["world", "niche"]),

    # ── Latin America ────────────────────────────────────────────────────────
    _s("Folha de S.Paulo (Brazil)", "https://www.folha.uol.com.br/",
       "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
       "BR", ["pt"], ["general", "world", "politics"]),
    _s("O Globo (Brazil)", "https://oglobo.globo.com/", "https://oglobo.globo.com/rss/oglobo",
       "BR", ["pt"], ["general", "world"]),
    _s("G1 (Globo, Brazil)", "https://g1.globo.com/", "https://g1.globo.com/dynamo/rss2.xml",
       "BR", ["pt"], ["general", "world"]),
    _s("Valor Econômico (Brazil)", "https://valor.globo.com/", "https://pox.globo.com/rss/valor",
       "BR", ["pt"], ["economy", "markets", "business"]),
    _s("Clarín (Argentina)", "https://www.clarin.com/", "https://www.clarin.com/rss/lo-ultimo/",
       "AR", ["es"], ["general", "world"]),
    _s("La Nación (Argentina)", "https://www.lanacion.com.ar/", "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml",
       "AR", ["es"], ["general", "politics"]),
    _s("El Mercurio / Emol (Chile)", "https://www.emol.com/", "https://www.emol.com/rss/rss.asp?canal=todas",
       "CL", ["es"], ["general", "economy"]),
    _s("El Tiempo (Colombia)", "https://www.eltiempo.com/", "https://www.eltiempo.com/rss/mundo.xml",
       "CO", ["es"], ["general", "world"]),
    _s("El Comercio (Peru)", "https://elcomercio.pe/", "https://elcomercio.pe/arcio/rss/",
       "PE", ["es"], ["general", "world"]),
    _s("Infobae", "https://www.infobae.com/", "https://www.infobae.com/feeds/rss/",
       "AR", ["es"], ["general", "world"]),

    # ── Science: major outlets & journals ────────────────────────────────────
    _s("Nature — Latest research", "https://www.nature.com/", "https://www.nature.com/nature/articles?type=article.rss",
       "GLOBAL", ["en"], ["science", "research"]),
    _s("Science / AAAS — News", "https://www.science.org/news", "https://www.science.org/rss/news_current.xml",
       "GLOBAL", ["en"], ["science", "research"], bot_sensitivity=1),
    _s("Science (current issue)", "https://www.science.org/journal/science", "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science",
       "GLOBAL", ["en"], ["science", "research"], bot_sensitivity=1),
    _s("EurekAlert! (AAAS)", "https://www.eurekalert.org/", "https://www.eurekalert.org/rss/all.xml",
       "GLOBAL", ["en"], ["science", "research", "press-release"]),
    _s("Phys.org", "https://phys.org/", "https://phys.org/rss-feed/",
       "GLOBAL", ["en"], ["science", "physics", "research"]),
    _s("ScienceDaily", "https://www.sciencedaily.com/", "https://www.sciencedaily.com/rss/all.xml",
       "GLOBAL", ["en"], ["science", "research"]),
    _s("Scientific American", "https://www.scientificamerican.com/", "https://www.scientificamerican.com/feed/rss/",
       "US", ["en"], ["science"], bot_sensitivity=1),
    _s("Quanta Magazine", "https://www.quantamagazine.org/", "https://www.quantamagazine.org/feed/",
       "US", ["en"], ["science", "mathematics", "physics", "niche"]),
    _s("Live Science", "https://www.livescience.com/", "https://www.livescience.com/feeds/all",
       "US", ["en"], ["science"]),
    _s("Space.com", "https://www.space.com/", "https://www.space.com/feeds/all",
       "US", ["en"], ["science", "space", "niche"]),
    _s("NASA — Breaking News", "https://www.nasa.gov/", "https://www.nasa.gov/rss/dyn/breaking_news.rss",
       "US", ["en"], ["science", "space", "research"]),
    _s("ESA — Space News", "https://www.esa.int/", "https://www.esa.int/rssfeed/Our_Activities/Space_News",
       "EU", ["en"], ["science", "space", "niche"]),
    _s("Nature Medicine", "https://www.nature.com/nm/", "https://www.nature.com/nm.rss",
       "GLOBAL", ["en"], ["science", "medicine", "research", "niche"]),
    _s("The Lancet — Online First", "https://www.thelancet.com/", "https://www.thelancet.com/rssfeed/lancet_online.xml",
       "GLOBAL", ["en"], ["science", "medicine", "research", "niche"], bot_sensitivity=1),
    _s("PLOS ONE", "https://journals.plos.org/plosone/", "https://journals.plos.org/plosone/feed/atom",
       "GLOBAL", ["en"], ["science", "research", "niche"]),
    _s("PNAS — Current Issue", "https://www.pnas.org/", "https://www.pnas.org/action/showFeed?type=etoc&feed=rss&jc=pnas",
       "GLOBAL", ["en"], ["science", "research", "niche"], bot_sensitivity=1),
    _s("Cell — Current Issue", "https://www.cell.com/cell/home", "https://www.cell.com/cell/inpress.rss",
       "GLOBAL", ["en"], ["science", "biology", "research", "niche"], bot_sensitivity=1),
    _s("IEEE Spectrum", "https://spectrum.ieee.org/", "https://spectrum.ieee.org/rss/fulltext",
       "US", ["en"], ["technology", "science", "engineering", "niche"]),

    # ── Science: arXiv (preprints, by subject) ───────────────────────────────
    _s("arXiv — Computer Science (cs)", "https://arxiv.org/list/cs/recent", "http://export.arxiv.org/rss/cs",
       "GLOBAL", ["en"], ["science", "technology", "research", "niche"]),
    _s("arXiv — Economics (econ)", "https://arxiv.org/list/econ/recent", "http://export.arxiv.org/rss/econ",
       "GLOBAL", ["en"], ["science", "economy", "research", "niche"]),
    _s("arXiv — Quantitative Finance (q-fin)", "https://arxiv.org/list/q-fin/recent", "http://export.arxiv.org/rss/q-fin",
       "GLOBAL", ["en"], ["science", "finance", "research", "niche"]),
    _s("arXiv — Physics", "https://arxiv.org/list/physics/recent", "http://export.arxiv.org/rss/physics",
       "GLOBAL", ["en"], ["science", "physics", "research", "niche"]),
    _s("arXiv — Mathematics (math)", "https://arxiv.org/list/math/recent", "http://export.arxiv.org/rss/math",
       "GLOBAL", ["en"], ["science", "mathematics", "research", "niche"]),
    _s("arXiv — Quantitative Biology (q-bio)", "https://arxiv.org/list/q-bio/recent", "http://export.arxiv.org/rss/q-bio",
       "GLOBAL", ["en"], ["science", "biology", "research", "niche"]),
    _s("arXiv — Statistics (stat)", "https://arxiv.org/list/stat/recent", "http://export.arxiv.org/rss/stat",
       "GLOBAL", ["en"], ["science", "statistics", "research", "niche"]),
    _s("arXiv — Astrophysics (astro-ph)", "https://arxiv.org/list/astro-ph/recent", "http://export.arxiv.org/rss/astro-ph",
       "GLOBAL", ["en"], ["science", "astrophysics", "research", "niche"]),
    _s("arXiv — Electrical Eng & Systems (eess)", "https://arxiv.org/list/eess/recent", "http://export.arxiv.org/rss/eess",
       "GLOBAL", ["en"], ["science", "engineering", "research", "niche"]),

    # ── Science / university press offices (long-tail) ───────────────────────
    _s("MIT News", "https://news.mit.edu/", "https://news.mit.edu/rss/feed",
       "US", ["en"], ["science", "technology", "research", "niche"]),
    _s("Stanford News", "https://news.stanford.edu/", "https://news.stanford.edu/feed/",
       "US", ["en"], ["science", "research", "niche"]),
    _s("Harvard Gazette", "https://news.harvard.edu/gazette/", "https://news.harvard.edu/gazette/feed/",
       "US", ["en"], ["science", "research", "niche"]),
    _s("Caltech News", "https://www.caltech.edu/about/news", "https://www.caltech.edu/about/news/rss",
       "US", ["en"], ["science", "research", "niche"]),
    _s("University of Cambridge — Research", "https://www.cam.ac.uk/research", "https://www.cam.ac.uk/news/feed",
       "GB", ["en"], ["science", "research", "niche"]),
    _s("University of Oxford — News", "https://www.ox.ac.uk/news", "https://www.ox.ac.uk/news/rss.xml",
       "GB", ["en"], ["science", "research", "niche"]),
    _s("Max Planck Society", "https://www.mpg.de/en", "https://www.mpg.de/rss/institute",
       "DE", ["en"], ["science", "research", "niche"]),
    _s("CERN — News", "https://home.cern/news", "https://home.cern/api/news/news/feed.rss",
       "CH", ["en"], ["science", "physics", "research", "niche"]),

    # ── Economy / finance / markets (specialist & long-tail) ─────────────────
    _s("IMF — News", "https://www.imf.org/", "https://www.imf.org/en/News/RSS?Language=ENG",
       "GLOBAL", ["en"], ["economy", "policy", "niche"]),
    _s("World Bank — News", "https://www.worldbank.org/", "https://www.worldbank.org/en/news/all?format=rss",
       "GLOBAL", ["en"], ["economy", "development", "policy", "niche"]),
    _s("OECD — Newsroom", "https://www.oecd.org/", "https://www.oecd.org/newsroom/rss.xml",
       "GLOBAL", ["en"], ["economy", "policy", "niche"]),
    _s("European Central Bank — Press", "https://www.ecb.europa.eu/", "https://www.ecb.europa.eu/rss/press.html",
       "EU", ["en"], ["economy", "finance", "policy", "niche"]),
    _s("Bank for International Settlements", "https://www.bis.org/", "https://www.bis.org/list/press_rss.rss",
       "GLOBAL", ["en"], ["economy", "finance", "policy", "niche"]),
    _s("Financial Times — Markets", "https://www.ft.com/markets", "https://www.ft.com/markets?format=rss",
       "GB", ["en"], ["markets", "finance"], bot_sensitivity=2),
    _s("Investing.com — News", "https://www.investing.com/", "https://www.investing.com/rss/news.rss",
       "GLOBAL", ["en"], ["markets", "finance", "niche"], bot_sensitivity=1),
    _s("Seeking Alpha — Market News", "https://seekingalpha.com/", "https://seekingalpha.com/market_currents.xml",
       "US", ["en"], ["markets", "finance", "equities", "niche"], bot_sensitivity=2),
    _s("CoinDesk (crypto)", "https://www.coindesk.com/", "https://www.coindesk.com/arc/outboundfeeds/rss/",
       "US", ["en"], ["finance", "crypto", "technology", "niche"]),
    _s("Cointelegraph (crypto)", "https://cointelegraph.com/", "https://cointelegraph.com/rss",
       "GLOBAL", ["en"], ["finance", "crypto", "niche"]),
    _s("The Block (crypto)", "https://www.theblock.co/", "https://www.theblock.co/rss.xml",
       "US", ["en"], ["finance", "crypto", "niche"]),

    # ── Technology / sector trade (long-tail / niche) ────────────────────────
    _s("AnandTech (hardware)", "https://www.anandtech.com/", "https://www.anandtech.com/rss/",
       "US", ["en"], ["technology", "hardware", "niche"]),
    _s("Tom's Hardware", "https://www.tomshardware.com/", "https://www.tomshardware.com/feeds/all",
       "US", ["en"], ["technology", "hardware", "niche"]),
    _s("The Stack (enterprise IT)", "https://www.thestack.technology/", "https://www.thestack.technology/rss/",
       "GB", ["en"], ["technology", "enterprise", "niche"]),
    _s("Krebs on Security", "https://krebsonsecurity.com/", "https://krebsonsecurity.com/feed/",
       "US", ["en"], ["technology", "security", "niche"]),
    _s("BleepingComputer (security)", "https://www.bleepingcomputer.com/", "https://www.bleepingcomputer.com/feed/",
       "US", ["en"], ["technology", "security", "niche"]),
    _s("The Hacker News (infosec)", "https://thehackernews.com/", "https://feeds.feedburner.com/TheHackersNews",
       "GLOBAL", ["en"], ["technology", "security", "niche"]),
    _s("AI News (artificialintelligence-news)", "https://www.artificialintelligence-news.com/",
       "https://www.artificialintelligence-news.com/feed/",
       "GLOBAL", ["en"], ["technology", "ai", "niche"]),
    _s("Semiconductor Engineering", "https://semiengineering.com/", "https://semiengineering.com/feed/",
       "US", ["en"], ["technology", "semiconductors", "niche"]),
    _s("Electrek (EV / energy)", "https://electrek.co/", "https://electrek.co/feed/",
       "US", ["en"], ["technology", "energy", "automotive", "niche"]),
    _s("Autocar (automotive)", "https://www.autocar.co.uk/", "https://www.autocar.co.uk/rss",
       "GB", ["en"], ["automotive", "niche"]),

    # ── Energy / climate / commodities (niche / long-tail) ───────────────────
    _s("OilPrice.com", "https://oilprice.com/", "https://oilprice.com/rss/main",
       "GLOBAL", ["en"], ["energy", "commodities", "markets", "niche"]),
    _s("S&P Global Commodity Insights", "https://www.spglobal.com/commodityinsights/",
       "https://www.spglobal.com/commodityinsights/en/rss-feed/news",
       "GLOBAL", ["en"], ["energy", "commodities", "markets", "niche"], bot_sensitivity=1),
    _s("Carbon Brief (climate)", "https://www.carbonbrief.org/", "https://www.carbonbrief.org/feed/",
       "GB", ["en"], ["science", "climate", "energy", "niche"]),
    _s("Inside Climate News", "https://insideclimatenews.org/", "https://insideclimatenews.org/feed/",
       "US", ["en"], ["science", "climate", "environment", "niche"]),
    _s("International Energy Agency (IEA)", "https://www.iea.org/", "https://www.iea.org/rss/news",
       "GLOBAL", ["en"], ["energy", "policy", "economy", "niche"]),

    # ── Health / medicine trade (niche) ──────────────────────────────────────
    _s("STAT News (health/biotech)", "https://www.statnews.com/", "https://www.statnews.com/feed/",
       "US", ["en"], ["science", "medicine", "biotech", "niche"]),
    _s("Endpoints News (biopharma)", "https://endpts.com/", "https://endpts.com/feed/",
       "US", ["en"], ["business", "biotech", "medicine", "niche"], bot_sensitivity=1),
    _s("FierceBiotech", "https://www.fiercebiotech.com/", "https://www.fiercebiotech.com/rss/xml",
       "US", ["en"], ["business", "biotech", "niche"]),
    _s("MedPage Today", "https://www.medpagetoday.com/", "https://www.medpagetoday.com/rss/headlines.xml",
       "US", ["en"], ["science", "medicine", "niche"]),

    # ── Defense / aerospace / geopolitics (niche) ────────────────────────────
    _s("Defense News", "https://www.defensenews.com/", "https://www.defensenews.com/arc/outboundfeeds/rss/",
       "US", ["en"], ["defense", "geopolitics", "niche"]),
    _s("Breaking Defense", "https://breakingdefense.com/", "https://breakingdefense.com/feed/",
       "US", ["en"], ["defense", "niche"]),
    _s("Aviation Week", "https://aviationweek.com/", "https://aviationweek.com/rss.xml",
       "US", ["en"], ["aerospace", "business", "niche"], bot_sensitivity=1),
    _s("War on the Rocks", "https://warontherocks.com/", "https://warontherocks.com/feed/",
       "US", ["en"], ["defense", "geopolitics", "niche"]),

    # ── Agriculture / shipping / industry trade (long-tail) ──────────────────
    _s("AgWeb (agriculture)", "https://www.agweb.com/", "https://www.agweb.com/rss.xml",
       "US", ["en"], ["agriculture", "commodities", "niche"]),
    _s("Lloyd's List (shipping)", "https://www.lloydslist.com/", None,
       "GB", ["en"], ["shipping", "logistics", "niche"], bot_sensitivity=2),
    _s("Maritime Executive", "https://maritime-executive.com/", "https://maritime-executive.com/rss",
       "GLOBAL", ["en"], ["shipping", "logistics", "niche"]),
    _s("FreightWaves (logistics)", "https://www.freightwaves.com/", "https://www.freightwaves.com/news/feed",
       "US", ["en"], ["logistics", "business", "niche"]),
    _s("Mining.com", "https://www.mining.com/", "https://www.mining.com/feed/",
       "GLOBAL", ["en"], ["mining", "commodities", "niche"]),

    # ── Media / culture / sports (breadth) ───────────────────────────────────
    _s("Variety (entertainment)", "https://variety.com/", "https://variety.com/feed/",
       "US", ["en"], ["entertainment", "business", "niche"]),
    _s("ESPN — Top Headlines", "https://www.espn.com/", "https://www.espn.com/espn/rss/news",
       "US", ["en"], ["sports", "general"]),
    _s("BBC Sport", "https://www.bbc.com/sport", "http://feeds.bbci.co.uk/sport/rss.xml",
       "GB", ["en"], ["sports"]),

    # ── HTML-only / API-only & bot-sensitive (no public RSS) ─────────────────
    _s("Bloomberg (homepage crawl)", "https://www.bloomberg.com/", None,
       "US", ["en"], ["business", "markets"], fetch_method="html", bot_sensitivity=3),
    _s("Reuters (homepage crawl)", "https://www.reuters.com/world/", None,
       "US", ["en"], ["world", "general"], fetch_method="html", bot_sensitivity=2),
    _s("People's Daily (China)", "http://en.people.cn/", None,
       "CN", ["en"], ["general", "politics"], fetch_method="html", bot_sensitivity=1),
    _s("GDELT — Latin America expansion", "https://www.gdeltproject.org/#latam", None,
       "LATAM", ["es", "pt"], ["general", "world"], api_kind="gdelt"),
    _s("GDELT — Africa expansion", "https://www.gdeltproject.org/#africa", None,
       "AF", ["en", "fr", "ar"], ["general", "world"], api_kind="gdelt"),
]


# ── Live-coverage corrections (2026-06-01) ───────────────────────────────────
# Applied after the literal catalog so every fix the live probe surfaced
# (docs/SOURCE_COVERAGE.md · `python -m newskoo.sources.validate`) is auditable in
# one place. fix_url = feed moved to a verified new URL; bot_sensitivity bump =
# 403 bot-wall (URL still valid, recovered in prod via UA rotation / headless
# browser); html = public feed retired → crawl the homepage instead.
_CORRECTIONS: dict[str, dict[str, Any]] = {
    # feed moved → corrected URL (verified live by web research)
    "The Globe and Mail": {"feed_url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/?outputType=xml"},
    "El Universal (Mexico)": {"feed_url": "https://www.eluniversal.com.mx/arc/outboundfeeds/rss/?outputType=xml"},
    "RTBF (Belgium, FR)": {"feed_url": "https://rss.rtbf.be/article/rss/rtbfinfo_homepage.xml"},
    "Gazeta Wyborcza (Poland)": {"feed_url": "https://serwisy.gazeta.pl/pub/rss/najnowsze_wyborcza.xml"},
    "Kyiv Independent (Ukraine)": {"feed_url": "https://kyivindependent.com/news-archive/rss/"},
    "Haaretz (English)": {"feed_url": "https://www.haaretz.com/cmlink/1.4605102"},
    "The National (UAE)": {"feed_url": "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml"},
    "The Jakarta Post": {"feed_url": "https://rss.thejakartapost.com/home"},
    "Kompas (Indonesia)": {"feed_url": "https://www.kompas.com/getrss/nasional", "bot_sensitivity": 3},
    "The Korea Herald": {"feed_url": "https://www.koreaherald.com/rss/newsAll"},
    "Caixin Global (China, EN)": {"feed_url": "https://gateway.caixin.com/api/data/global/feedlyRss.xml"},
    "Focus Taiwan (CNA, EN)": {"feed_url": "https://feeds.feedburner.com/rsscna/engnews"},
    "El Mercurio / Emol (Chile)": {"feed_url": "http://rss.emol.com/rss.asp?canal=0"},
    "Infobae": {"feed_url": "https://www.infobae.com/arc/outboundfeeds/rss/?outputType=xml"},
    # "Nature (journal)" already serves nature.com/nature.rss → this one crawls html
    "Nature — Latest research": {"feed_url": None, "fetch_method": "html"},
    "Scientific American": {"feed_url": "http://rss.sciam.com/ScientificAmerican-Global"},
    "arXiv — Computer Science (cs)": {"feed_url": "https://rss.arxiv.org/rss/cs"},
    "arXiv — Economics (econ)": {"feed_url": "https://rss.arxiv.org/rss/econ"},
    "arXiv — Quantitative Finance (q-fin)": {"feed_url": "https://rss.arxiv.org/rss/q-fin"},
    "arXiv — Physics": {"feed_url": "https://rss.arxiv.org/rss/physics"},
    "arXiv — Mathematics (math)": {"feed_url": "https://rss.arxiv.org/rss/math"},
    "arXiv — Quantitative Biology (q-bio)": {"feed_url": "https://rss.arxiv.org/rss/q-bio"},
    "arXiv — Statistics (stat)": {"feed_url": "https://rss.arxiv.org/rss/stat"},
    "arXiv — Astrophysics (astro-ph)": {"feed_url": "https://rss.arxiv.org/rss/astro-ph"},
    "arXiv — Electrical Eng & Systems (eess)": {"feed_url": "https://rss.arxiv.org/rss/eess"},
    "University of Oxford — News": {"feed_url": "https://www.ox.ac.uk/feeds/rss/news", "bot_sensitivity": 3},
    "CERN — News": {"feed_url": "https://home.cern/api/news/feed.rss", "bot_sensitivity": 3},
    "Bank for International Settlements": {"feed_url": "https://www.bis.org/doclist/all_pressrels.rss"},
    "Maritime Executive": {"feed_url": "https://maritime-executive.com/articles.rss"},
    # 403 bot-wall — URL valid; raise politeness tier (crawler uses a browser UA)
    "Politico": {"bot_sensitivity": 3},
    "Les Échos": {"bot_sensitivity": 3},
    "Expresso (Portugal)": {"bot_sensitivity": 3},
    "Kathimerini (Greece, EN)": {"bot_sensitivity": 3},
    "TVN24 (Poland)": {"bot_sensitivity": 3},
    "Al Arabiya (Arabic)": {"bot_sensitivity": 3},
    "The Times of Israel": {"bot_sensitivity": 3},
    "The Punch (Nigeria)": {"bot_sensitivity": 3},
    "Ahram Online (Egypt)": {"bot_sensitivity": 3},
    "GhanaWeb": {"bot_sensitivity": 3},
    "The Herald (Zimbabwe)": {"bot_sensitivity": 3},
    "Philippine Daily Inquirer": {"bot_sensitivity": 3},
    "RNZ (New Zealand)": {"bot_sensitivity": 3},
    "MIT News": {"bot_sensitivity": 3},
    "Stanford News": {"bot_sensitivity": 3},
    "University of Cambridge — Research": {"bot_sensitivity": 3},
    "OECD — Newsroom": {"bot_sensitivity": 3},
    "S&P Global Commodity Insights": {"bot_sensitivity": 3},
    "International Energy Agency (IEA)": {"bot_sensitivity": 3},
    "Endpoints News (biopharma)": {"bot_sensitivity": 3},
    "AgWeb (agriculture)": {"bot_sensitivity": 3},
    # public RSS retired → crawl the homepage (html)
    "Reuters — World": {"feed_url": None, "fetch_method": "html"},
    "Reuters — Business": {"feed_url": None, "fetch_method": "html"},
    "USA Today": {"feed_url": None, "fetch_method": "html"},
    "Milenio": {"feed_url": None, "fetch_method": "html"},
    "Swissinfo (CH)": {"feed_url": None, "fetch_method": "html"},
    "Gulf News (UAE)": {"feed_url": None, "fetch_method": "html"},
    "NHK World (English)": {"feed_url": None, "fetch_method": "html"},
    "ABC (Pacific Beat)": {"feed_url": None, "fetch_method": "html"},
    "Max Planck Society": {"feed_url": None, "fetch_method": "html"},
    "IMF — News": {"feed_url": None, "fetch_method": "html"},
    "World Bank — News": {"feed_url": None, "fetch_method": "html"},
    "AnandTech (hardware)": {"feed_url": None, "fetch_method": "html"},
    "EurekAlert! (AAAS)": {"feed_url": None, "fetch_method": "html"},
}


def _apply_corrections(
    sources: list[dict[str, Any]], corrections: dict[str, dict[str, Any]]
) -> list[dict[str, Any]]:
    """Patch seed entries in place from live-probe corrections (by name)."""
    by_name = {s["name"]: s for s in sources}
    for name, patch in corrections.items():
        target = by_name.get(name)
        if target is None:
            log.warning("seed.correction_unmatched", name=name)
            continue
        target.update(patch)
    return sources


SEED_SOURCES = _apply_corrections(SEED_SOURCES, _CORRECTIONS)


async def seed_sources(session: AsyncSession) -> int:
    """Upsert every entry in :data:`SEED_SOURCES` (idempotent). Returns count."""
    count = 0
    for entry in SEED_SOURCES:
        payload = SourceCreate.model_validate(entry)
        await upsert_source(session, payload)
        count += 1
    log.info("sources.seeded", count=count, total=len(SEED_SOURCES))
    return count
