"""Report export helpers (markdown; PDF is an optional future add-on)."""

from __future__ import annotations

from newskoo.reports.schemas import ReportResult


def to_markdown(report: ReportResult) -> str:
    """Render a report (with a small front-matter header + citation footer)."""
    lines = [
        f"# {report.title}",
        "",
        report.body_md.strip(),
        "",
        "---",
        "",
        "## Citations",
    ]
    if report.citations.events:
        ids = ", ".join(f"E{i}" for i in report.citations.events)
        lines.append(f"- Events: {ids}")
    if report.citations.articles:
        ids = ", ".join(f"A{i}" for i in report.citations.articles)
        lines.append(f"- Articles: {ids}")
    if report.provider:
        lines.append("")
        lines.append(f"_Generated by {report.provider}/{report.model}._")
    return "\n".join(lines)
