"""Baseline schema for NewsKoo (hand-written; not autogenerated).

Creates the full Phase-1 structured backbone exactly matching the SQLAlchemy
ORM in ``newskoo.models``:

    sources, events, entities, keywords, topics, articles, article_versions,
    article_entities, article_keywords, article_topics, event_articles,
    analysis, reports, mention_timeseries, crawl_log

Seeds the required PostgreSQL extensions (``vector`` for pgvector, ``pg_trgm``
for trigram lexical matching) and builds every index declared in the models'
``__table_args__`` plus **HNSW** vector indexes for the embedding columns.

The vector dimension is read from settings (``embedding_dim``) so it always
matches the ORM ``Vector`` columns.

revision = "0001"
down_revision = None
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from newskoo.core.config import get_settings
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# Alembic identifiers.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

_EMBED_DIM = get_settings().embedding_dim


def upgrade() -> None:
    # ── Extensions ──────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ── sources ─────────────────────────────────────────────────────────────
    op.create_table(
        "sources",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("homepage_url", sa.Text(), nullable=False),
        sa.Column("feed_url", sa.Text(), nullable=True),
        sa.Column("api_kind", sa.String(length=40), nullable=True),
        sa.Column("fetch_method", sa.String(length=10), nullable=False),
        sa.Column("region", sa.String(length=40), nullable=True),
        sa.Column("languages", sa.ARRAY(sa.String(length=8)), nullable=False),
        sa.Column("categories", sa.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("bot_sensitivity", sa.SmallInteger(), nullable=False),
        sa.Column("politeness", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("robots_url", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("health", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── events ──────────────────────────────────────────────────────────────
    # Created before articles because articles.event_id references it.
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("language_count", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("centroid", Vector(_EMBED_DIM), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── entities ────────────────────────────────────────────────────────────
    op.create_table(
        "entities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.String(length=400)), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", Vector(_EMBED_DIM), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "type", name="uq_entity_name_type"),
    )

    # ── keywords ────────────────────────────────────────────────────────────
    op.create_table(
        "keywords",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("term", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("term"),
    )

    # ── topics (self-referential taxonomy) ──────────────────────────────────
    op.create_table(
        "topics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )

    # ── articles ────────────────────────────────────────────────────────────
    # Depends on sources + events.
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("authors", sa.ARRAY(sa.String(length=200)), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(body,''))",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("embedding", Vector(_EMBED_DIM), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_articles_canonical_url", "articles", ["canonical_url"], unique=True)
    op.create_index(
        "ix_articles_source_published", "articles", ["source_id", "published_at"], unique=False
    )
    op.create_index("ix_articles_simhash", "articles", ["simhash"], unique=False)
    op.create_index(
        "ix_articles_tsv", "articles", ["tsv"], unique=False, postgresql_using="gin"
    )
    # HNSW vector index (pgvector >= 0.5): no training step, good recall/latency.
    op.execute(
        "CREATE INDEX ix_articles_embedding ON articles "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # ── article_versions ────────────────────────────────────────────────────
    op.create_table(
        "article_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── article_entities (composite PK association) ─────────────────────────
    op.create_table(
        "article_entities",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("salience", sa.Float(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "entity_id"),
    )
    op.create_index(
        "ix_article_entities_entity", "article_entities", ["entity_id"], unique=False
    )

    # ── article_keywords (composite PK association) ─────────────────────────
    op.create_table(
        "article_keywords",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("keyword_id", sa.BigInteger(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["keyword_id"], ["keywords.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "keyword_id"),
    )
    op.create_index(
        "ix_article_keywords_keyword", "article_keywords", ["keyword_id"], unique=False
    )

    # ── article_topics (composite PK association) ───────────────────────────
    op.create_table(
        "article_topics",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "topic_id"),
    )
    op.create_index(
        "ix_article_topics_topic", "article_topics", ["topic_id"], unique=False
    )

    # ── event_articles (composite PK association) ───────────────────────────
    op.create_table(
        "event_articles",
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("is_seed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "article_id"),
    )

    # ── analysis ────────────────────────────────────────────────────────────
    op.create_table(
        "analysis",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("target_type", sa.String(length=10), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_analysis_target", "analysis", ["target_type", "target_id", "kind"], unique=False
    )

    # ── reports ─────────────────────────────────────────────────────────────
    op.create_table(
        "reports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("scheduled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── mention_timeseries (composite PK, no surrogate id) ──────────────────
    op.create_table(
        "mention_timeseries",
        sa.Column("target_type", sa.String(length=10), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.DateTime(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("velocity", sa.Float(), nullable=False),
        sa.Column("zscore", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("target_type", "target_id", "bucket"),
    )

    # ── crawl_log ───────────────────────────────────────────────────────────
    op.create_table(
        "crawl_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_crawl_log_source_time", "crawl_log", ["source_id", "fetched_at"], unique=False
    )

    # HNSW vector indexes for entity / event embeddings.
    op.execute(
        "CREATE INDEX ix_entities_embedding ON entities "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_events_centroid ON events "
        "USING hnsw (centroid vector_cosine_ops)"
    )


def downgrade() -> None:
    # Drop in reverse dependency order. Indexes created via raw SQL are dropped
    # explicitly; index objects created with create_index drop with their table.
    op.execute("DROP INDEX IF EXISTS ix_events_centroid")
    op.execute("DROP INDEX IF EXISTS ix_entities_embedding")

    op.drop_index("ix_crawl_log_source_time", table_name="crawl_log")
    op.drop_table("crawl_log")

    op.drop_table("mention_timeseries")

    op.drop_table("reports")

    op.drop_index("ix_analysis_target", table_name="analysis")
    op.drop_table("analysis")

    op.drop_table("event_articles")

    op.drop_index("ix_article_topics_topic", table_name="article_topics")
    op.drop_table("article_topics")

    op.drop_index("ix_article_keywords_keyword", table_name="article_keywords")
    op.drop_table("article_keywords")

    op.drop_index("ix_article_entities_entity", table_name="article_entities")
    op.drop_table("article_entities")

    op.drop_table("article_versions")

    op.execute("DROP INDEX IF EXISTS ix_articles_embedding")
    op.drop_index("ix_articles_tsv", table_name="articles")
    op.drop_index("ix_articles_simhash", table_name="articles")
    op.drop_index("ix_articles_source_published", table_name="articles")
    op.drop_index("ix_articles_canonical_url", table_name="articles")
    op.drop_table("articles")

    op.drop_table("topics")
    op.drop_table("keywords")
    op.drop_table("entities")
    op.drop_table("events")
    op.drop_table("sources")

    # Extensions are left in place: other databases/roles may depend on them,
    # and dropping them is rarely desired on downgrade.
