"""Financial / equities signal layer (hand-written; not autogenerated).

Adds the three tables that back NewsKoo's signal layer, matching the SQLAlchemy
ORM in ``newskoo.models.finance`` exactly (types, FKs + ondelete, composite PK,
``Vector(embedding_dim)`` columns, and every declared index):

    securities, entity_securities, signals

The ``vector`` extension is already created by the 0001 baseline, so it is not
re-created here. A **HNSW** index is built on ``securities.embedding`` (matching
the baseline's vector-index choice: no training step, good recall/latency).

The vector dimension is read from settings (``embedding_dim``) so it always
matches the ORM ``Vector`` columns.

revision = "0002"
down_revision = "0001"
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from newskoo.core.config import get_settings
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# Alembic identifiers.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None

_EMBED_DIM = get_settings().embedding_dim


def upgrade() -> None:
    # ── securities ──────────────────────────────────────────────────────────
    op.create_table(
        "securities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("exchange", sa.String(length=40), nullable=True),
        sa.Column("mic", sa.String(length=8), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("asset_class", sa.String(length=20), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.String(length=400)), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", Vector(_EMBED_DIM), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_securities_symbol", "securities", ["symbol"], unique=True)
    op.create_index("ix_securities_name", "securities", ["name"], unique=False)
    # HNSW vector index (pgvector >= 0.5): no training step, good recall/latency.
    op.execute(
        "CREATE INDEX ix_securities_embedding ON securities "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # ── entity_securities (composite PK association) ────────────────────────
    op.create_table(
        "entity_securities",
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["security_id"], ["securities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entity_id", "security_id"),
    )
    op.create_index(
        "ix_entity_securities_security", "entity_securities", ["security_id"], unique=False
    )

    # ── signals (append-only point-in-time; created_at only) ────────────────
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_hours", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("supporting_article_ids", sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("supporting_event_ids", sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["security_id"], ["securities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signals_security_as_of", "signals", ["security_id", "as_of"], unique=False
    )


def downgrade() -> None:
    # Drop in reverse dependency order. Indexes created via raw SQL are dropped
    # explicitly; index objects created with create_index drop with their table.
    op.drop_index("ix_signals_security_as_of", table_name="signals")
    op.drop_table("signals")

    op.drop_index("ix_entity_securities_security", table_name="entity_securities")
    op.drop_table("entity_securities")

    op.execute("DROP INDEX IF EXISTS ix_securities_embedding")
    op.drop_index("ix_securities_name", table_name="securities")
    op.drop_index("ix_securities_symbol", table_name="securities")
    op.drop_table("securities")

    # The ``vector`` extension is left in place (owned by the 0001 baseline).
