"""Extra seed sources — AFRICA + MIDDLE EAST depth bucket.

Hand-curated, individually live-verified RSS/Atom feeds expanding worldwide
coverage across West/East/Southern/North Africa and the Middle East. Focus is
on regional/local outlets, language-native press (Arabic, French, Swahili,
Hebrew, Persian, Turkish), business/economy, and energy/commodities — outlets
NOT already present in the main ``SEED_SOURCES`` catalog.

Every ``rss`` entry below was fetched with a desktop browser User-Agent and
confirmed to return a parseable feed (``<rss>``/``<feed>``/``<rdf>`` with at
least one ``<item>``/``<entry>``) on verification day (2026-06). A handful of
strong outlets with no working public feed are included as ``html`` homepage
crawls (``feed_url=None``).

Consumed exactly like the main catalog: each entry is a plain dict with the keys
``name, homepage_url, feed_url, api_kind, fetch_method, region, languages,
categories, bot_sensitivity``.
"""

from __future__ import annotations

SOURCES: list[dict] = [
    # ── West Africa: Nigeria (English) ───────────────────────────────────────
    {"name": "Vanguard (Nigeria)", "homepage_url": "https://www.vanguardngr.com/",
     "feed_url": "https://www.vanguardngr.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "Daily Post (Nigeria)", "homepage_url": "https://dailypost.ng/",
     "feed_url": "https://dailypost.ng/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "TheCable (Nigeria)", "homepage_url": "https://www.thecable.ng/",
     "feed_url": "https://www.thecable.ng/feed", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "politics", "investigative"], "bot_sensitivity": 0},
    {"name": "BusinessDay (Nigeria)", "homepage_url": "https://businessday.ng/",
     "feed_url": "https://businessday.ng/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["business", "economy", "markets"], "bot_sensitivity": 0},
    {"name": "Nairametrics (Nigeria business/finance)", "homepage_url": "https://nairametrics.com/",
     "feed_url": "https://nairametrics.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["business", "economy", "markets", "finance", "niche"], "bot_sensitivity": 0},
    {"name": "Channels Television (Nigeria)", "homepage_url": "https://www.channelstv.com/",
     "feed_url": "https://www.channelstv.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Legit.ng (Nigeria)", "homepage_url": "https://www.legit.ng/",
     "feed_url": "https://www.legit.ng/rss/all.rss", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Peoples Gazette (Nigeria)", "homepage_url": "https://www.peoplesgazette.com/",
     "feed_url": "https://www.peoplesgazette.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "politics", "investigative"], "bot_sensitivity": 0},
    {"name": "Leadership (Nigeria)", "homepage_url": "https://leadership.ng/",
     "feed_url": "https://leadership.ng/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "The Sun (Nigeria)", "homepage_url": "https://www.sunnewsonline.com/",
     "feed_url": "https://www.sunnewsonline.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "PM News (Nigeria)", "homepage_url": "https://www.pmnewsnigeria.com/",
     "feed_url": "https://www.pmnewsnigeria.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Naija247news (Nigeria business)", "homepage_url": "https://www.naija247news.com/",
     "feed_url": "https://www.naija247news.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["business", "economy", "markets"], "bot_sensitivity": 0},
    {"name": "TheWill (Nigeria)", "homepage_url": "https://thewillnigeria.com/",
     "feed_url": "https://thewillnigeria.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "TechCabal (African tech/startups)", "homepage_url": "https://techcabal.com/",
     "feed_url": "https://techcabal.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NG", "languages": ["en"],
     "categories": ["technology", "startups", "business", "niche"], "bot_sensitivity": 0},
    {"name": "Disrupt Africa (startups/VC)", "homepage_url": "https://disrupt-africa.com/",
     "feed_url": "https://disrupt-africa.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["en"],
     "categories": ["technology", "startups", "business", "niche"], "bot_sensitivity": 0},

    # ── West Africa: Ghana (English) ─────────────────────────────────────────
    {"name": "MyJoyOnline (Ghana)", "homepage_url": "https://www.myjoyonline.com/",
     "feed_url": "https://www.myjoyonline.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "GH", "languages": ["en"],
     "categories": ["general", "politics", "business"], "bot_sensitivity": 0},
    {"name": "GBC Ghana Online", "homepage_url": "https://gbcghanaonline.com/",
     "feed_url": "https://gbcghanaonline.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "GH", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "3News (Ghana)", "homepage_url": "https://3news.com/",
     "feed_url": "https://3news.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "GH", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "Ghana Business News", "homepage_url": "https://www.ghanabusinessnews.com/",
     "feed_url": "https://www.ghanabusinessnews.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "GH", "languages": ["en"],
     "categories": ["business", "economy", "markets", "niche"], "bot_sensitivity": 0},

    # ── West Africa: francophone & Senegal/Côte d'Ivoire ─────────────────────
    {"name": "Jeune Afrique", "homepage_url": "https://www.jeuneafrique.com/",
     "feed_url": "https://www.jeuneafrique.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["fr"],
     "categories": ["general", "politics", "business", "world"], "bot_sensitivity": 0},
    {"name": "RFI Afrique", "homepage_url": "https://www.rfi.fr/fr/afrique/",
     "feed_url": "https://www.rfi.fr/fr/afrique/rss", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["fr"],
     "categories": ["general", "world", "politics"], "bot_sensitivity": 0},
    {"name": "Dakaractu (Senegal)", "homepage_url": "https://www.dakaractu.com/",
     "feed_url": "https://www.dakaractu.com/xml/syndication.rss", "api_kind": None,
     "fetch_method": "rss", "region": "SN", "languages": ["fr"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "AllAfrica — Senegal", "homepage_url": "https://allafrica.com/senegal/",
     "feed_url": "https://allafrica.com/tools/headlines/rdf/senegal/headlines.rdf", "api_kind": None,
     "fetch_method": "rss", "region": "SN", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},

    # ── East Africa: Kenya / Tanzania / Uganda / Ethiopia / Rwanda ───────────
    {"name": "Standard Media (Kenya)", "homepage_url": "https://www.standardmedia.co.ke/",
     "feed_url": "https://www.standardmedia.co.ke/rss/headlines.php", "api_kind": None,
     "fetch_method": "rss", "region": "KE", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Capital FM (Kenya)", "homepage_url": "https://www.capitalfm.co.ke/news/",
     "feed_url": "https://www.capitalfm.co.ke/news/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "KE", "languages": ["en"],
     "categories": ["general", "business"], "bot_sensitivity": 0},
    {"name": "Tuko (Kenya)", "homepage_url": "https://www.tuko.co.ke/",
     "feed_url": "https://www.tuko.co.ke/rss/all.rss", "api_kind": None,
     "fetch_method": "rss", "region": "KE", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Kenyans.co.ke", "homepage_url": "https://www.kenyans.co.ke/",
     "feed_url": "https://www.kenyans.co.ke/feeds/news", "api_kind": None,
     "fetch_method": "rss", "region": "KE", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "Business Daily Africa (Kenya)", "homepage_url": "https://www.businessdailyafrica.com/",
     "feed_url": "https://www.businessdailyafrica.com/bd/rss.xml", "api_kind": None,
     "fetch_method": "rss", "region": "KE", "languages": ["en"],
     "categories": ["business", "economy", "markets", "finance"], "bot_sensitivity": 0},
    {"name": "AllAfrica — Tanzania", "homepage_url": "https://allafrica.com/tanzania/",
     "feed_url": "https://allafrica.com/tools/headlines/rdf/tanzania/headlines.rdf", "api_kind": None,
     "fetch_method": "rss", "region": "TZ", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "AllAfrica — Uganda", "homepage_url": "https://allafrica.com/uganda/",
     "feed_url": "https://allafrica.com/tools/headlines/rdf/uganda/headlines.rdf", "api_kind": None,
     "fetch_method": "rss", "region": "UG", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "The Independent (Uganda)", "homepage_url": "https://www.independent.co.ug/",
     "feed_url": "https://www.independent.co.ug/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "UG", "languages": ["en"],
     "categories": ["general", "politics", "business"], "bot_sensitivity": 0},
    {"name": "The Observer (Uganda)", "homepage_url": "https://www.observer.ug/",
     "feed_url": "https://www.observer.ug/feed", "api_kind": None,
     "fetch_method": "rss", "region": "UG", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "AllAfrica — Ethiopia", "homepage_url": "https://allafrica.com/ethiopia/",
     "feed_url": "https://allafrica.com/tools/headlines/rdf/ethiopia/headlines.rdf", "api_kind": None,
     "fetch_method": "rss", "region": "ET", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Fana Broadcasting (Ethiopia, EN)", "homepage_url": "https://www.fanabc.com/english/",
     "feed_url": "https://www.fanabc.com/english/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "ET", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},

    # ── Swahili native-language (East Africa) ────────────────────────────────
    {"name": "BBC News Swahili", "homepage_url": "https://www.bbc.com/swahili",
     "feed_url": "https://www.bbc.com/swahili/index.xml", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["sw"],
     "categories": ["general", "world"], "bot_sensitivity": 0},

    # ── Southern Africa: South Africa / Zimbabwe / Zambia / Namibia ──────────
    {"name": "BusinessTech (South Africa)", "homepage_url": "https://businesstech.co.za/",
     "feed_url": "https://businesstech.co.za/news/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "ZA", "languages": ["en"],
     "categories": ["business", "economy", "technology", "niche"], "bot_sensitivity": 0},
    {"name": "Moneyweb (South Africa)", "homepage_url": "https://www.moneyweb.co.za/",
     "feed_url": "https://www.moneyweb.co.za/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "ZA", "languages": ["en"],
     "categories": ["business", "economy", "markets", "finance", "niche"], "bot_sensitivity": 0},
    {"name": "MiningMx (South Africa mining)", "homepage_url": "https://www.miningmx.com/",
     "feed_url": "https://www.miningmx.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "ZA", "languages": ["en"],
     "categories": ["business", "mining", "commodities", "niche"], "bot_sensitivity": 0},
    {"name": "New Zimbabwe", "homepage_url": "https://newzimbabwe.com/",
     "feed_url": "https://newzimbabwe.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "ZW", "languages": ["en"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "Lusaka Times (Zambia)", "homepage_url": "https://lusakatimes.com/",
     "feed_url": "https://lusakatimes.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "ZM", "languages": ["en"],
     "categories": ["general", "politics", "business"], "bot_sensitivity": 0},
    {"name": "The Namibian", "homepage_url": "https://www.namibian.com.na/",
     "feed_url": "https://www.namibian.com.na/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "NA", "languages": ["en"],
     "categories": ["general", "politics", "business"], "bot_sensitivity": 0},

    # ── North Africa: Egypt / Morocco / Algeria / Tunisia ────────────────────
    {"name": "Daily News Egypt", "homepage_url": "https://www.dailynewsegypt.com/",
     "feed_url": "https://www.dailynewsegypt.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "EG", "languages": ["en"],
     "categories": ["general", "business", "economy"], "bot_sensitivity": 0},
    {"name": "Mada Masr (Egypt, EN)", "homepage_url": "https://www.madamasr.com/en/",
     "feed_url": "https://www.madamasr.com/en/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "EG", "languages": ["en"],
     "categories": ["general", "politics", "investigative", "niche"], "bot_sensitivity": 0},
    {"name": "Hespress (Morocco, AR)", "homepage_url": "https://www.hespress.com/",
     "feed_url": "https://www.hespress.com/feed", "api_kind": None,
     "fetch_method": "rss", "region": "MA", "languages": ["ar"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "Hespress English (Morocco)", "homepage_url": "https://en.hespress.com/",
     "feed_url": "https://en.hespress.com/feed", "api_kind": None,
     "fetch_method": "rss", "region": "MA", "languages": ["en"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "AllAfrica — Morocco", "homepage_url": "https://allafrica.com/morocco/",
     "feed_url": "https://allafrica.com/tools/headlines/rdf/morocco/headlines.rdf", "api_kind": None,
     "fetch_method": "rss", "region": "MA", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "TSA (Tout sur l'Algérie)", "homepage_url": "https://www.tsa-algerie.com/",
     "feed_url": "https://www.tsa-algerie.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "DZ", "languages": ["fr"],
     "categories": ["general", "politics", "business"], "bot_sensitivity": 0},
    {"name": "El Watan (Algeria)", "homepage_url": "https://www.elwatan-dz.com/",
     "feed_url": "https://www.elwatan-dz.com/feed", "api_kind": None,
     "fetch_method": "rss", "region": "DZ", "languages": ["fr"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "Kapitalis (Tunisia)", "homepage_url": "https://kapitalis.com/",
     "feed_url": "https://kapitalis.com/tunisie/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "TN", "languages": ["fr"],
     "categories": ["general", "politics", "economy"], "bot_sensitivity": 0},

    # ── Pan-African business / energy / general ──────────────────────────────
    {"name": "Africanews", "homepage_url": "https://www.africanews.com/",
     "feed_url": "https://www.africanews.com/feed/rss", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["en"],
     "categories": ["general", "world", "business"], "bot_sensitivity": 0},
    {"name": "The Africa Report", "homepage_url": "https://www.theafricareport.com/",
     "feed_url": "https://www.theafricareport.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["en"],
     "categories": ["business", "economy", "politics", "niche"], "bot_sensitivity": 0},
    {"name": "African Business", "homepage_url": "https://african.business/",
     "feed_url": "https://african.business/feed", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["en"],
     "categories": ["business", "economy", "markets", "energy", "niche"], "bot_sensitivity": 0},
    {"name": "AllAfrica — Business", "homepage_url": "https://allafrica.com/business/",
     "feed_url": "https://allafrica.com/tools/headlines/rdf/business/headlines.rdf", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["en"],
     "categories": ["business", "economy", "markets"], "bot_sensitivity": 0},
    {"name": "AllAfrica — Sustainable Development", "homepage_url": "https://allafrica.com/sustainable/",
     "feed_url": "https://allafrica.com/tools/headlines/rdf/sustainable/headlines.rdf", "api_kind": None,
     "fetch_method": "rss", "region": "AF", "languages": ["en"],
     "categories": ["development", "environment", "energy", "niche"], "bot_sensitivity": 0},

    # ── Middle East: pan-regional & business / energy ────────────────────────
    {"name": "Saudi Gazette", "homepage_url": "https://saudigazette.com.sa/",
     "feed_url": "https://saudigazette.com.sa/rssFeed/74", "api_kind": None,
     "fetch_method": "rss", "region": "SA", "languages": ["en"],
     "categories": ["general", "business", "world"], "bot_sensitivity": 0},
    {"name": "Asharq Al-Awsat (AR)", "homepage_url": "https://aawsat.com/",
     "feed_url": "https://aawsat.com/feed", "api_kind": None,
     "fetch_method": "rss", "region": "SA", "languages": ["ar"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "Al-Quds Al-Arabi (AR)", "homepage_url": "https://www.alquds.co.uk/",
     "feed_url": "https://www.alquds.co.uk/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "JO", "languages": ["ar"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "Al-Araby Al-Jadeed (AR)", "homepage_url": "https://www.alaraby.co.uk/",
     "feed_url": "https://www.alaraby.co.uk/rss", "api_kind": None,
     "fetch_method": "rss", "region": "QA", "languages": ["ar"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "The New Arab (EN)", "homepage_url": "https://www.newarab.com/",
     "feed_url": "https://english.alaraby.co.uk/rss", "api_kind": None,
     "fetch_method": "rss", "region": "QA", "languages": ["en"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "Middle East Eye", "homepage_url": "https://www.middleeasteye.net/",
     "feed_url": "https://www.middleeasteye.net/rss.xml", "api_kind": None,
     "fetch_method": "rss", "region": "GLOBAL", "languages": ["en"],
     "categories": ["general", "politics", "world", "niche"], "bot_sensitivity": 0},
    {"name": "Middle East Monitor (MEMO)", "homepage_url": "https://www.middleeastmonitor.com/",
     "feed_url": "https://www.middleeastmonitor.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "GLOBAL", "languages": ["en"],
     "categories": ["general", "politics", "world", "niche"], "bot_sensitivity": 0},
    {"name": "Al-Monitor", "homepage_url": "https://www.al-monitor.com/",
     "feed_url": "https://www.al-monitor.com/rss", "api_kind": None,
     "fetch_method": "rss", "region": "GLOBAL", "languages": ["en"],
     "categories": ["general", "politics", "world", "niche"], "bot_sensitivity": 0},
    {"name": "Al Bawaba", "homepage_url": "https://www.albawaba.com/",
     "feed_url": "https://www.albawaba.com/rss/all", "api_kind": None,
     "fetch_method": "rss", "region": "JO", "languages": ["en"],
     "categories": ["general", "business", "world"], "bot_sensitivity": 0},

    # ── Middle East: Gulf / Qatar / Jordan ───────────────────────────────────
    {"name": "Doha News (Qatar)", "homepage_url": "https://www.dohanews.co/",
     "feed_url": "https://www.dohanews.co/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "QA", "languages": ["en"],
     "categories": ["general", "business", "world"], "bot_sensitivity": 0},
    {"name": "Roya News (Jordan, AR)", "homepage_url": "https://www.roya.tv/",
     "feed_url": "https://www.roya.tv/rss", "api_kind": None,
     "fetch_method": "rss", "region": "JO", "languages": ["ar"],
     "categories": ["general", "world"], "bot_sensitivity": 0},

    # ── Middle East: Israel (English & Hebrew) ───────────────────────────────
    {"name": "The Jerusalem Post — Front Page", "homepage_url": "https://www.jpost.com/",
     "feed_url": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", "api_kind": None,
     "fetch_method": "rss", "region": "IL", "languages": ["en"],
     "categories": ["general", "politics", "world"], "bot_sensitivity": 0},
    {"name": "Ynetnews (Israel, EN)", "homepage_url": "https://www.ynetnews.com/",
     "feed_url": "https://www.ynetnews.com/Integration/StoryRss3082.xml", "api_kind": None,
     "fetch_method": "rss", "region": "IL", "languages": ["en"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Ynet (Israel, HE)", "homepage_url": "https://www.ynet.co.il/",
     "feed_url": "https://www.ynet.co.il/Integration/StoryRss2.xml", "api_kind": None,
     "fetch_method": "rss", "region": "IL", "languages": ["he"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Haaretz (Hebrew)", "homepage_url": "https://www.haaretz.co.il/",
     "feed_url": "https://www.haaretz.co.il/srv/rss---feedly", "api_kind": None,
     "fetch_method": "rss", "region": "IL", "languages": ["he"],
     "categories": ["general", "politics"], "bot_sensitivity": 1},
    {"name": "Maariv (Israel, HE)", "homepage_url": "https://www.maariv.co.il/",
     "feed_url": "https://www.maariv.co.il/Rss/RssFeedsMivzakiChadashot", "api_kind": None,
     "fetch_method": "rss", "region": "IL", "languages": ["he"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "NoCamels (Israel tech/innovation)", "homepage_url": "https://nocamels.com/",
     "feed_url": "https://nocamels.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "IL", "languages": ["en"],
     "categories": ["technology", "startups", "science", "niche"], "bot_sensitivity": 0},

    # ── Middle East: Iran (Persian & English) ────────────────────────────────
    {"name": "IRNA (Iran, Persian)", "homepage_url": "https://www.irna.ir/",
     "feed_url": "https://www.irna.ir/rss", "api_kind": None,
     "fetch_method": "rss", "region": "IR", "languages": ["fa"],
     "categories": ["general", "world", "politics"], "bot_sensitivity": 0},
    {"name": "Press TV (Iran, EN)", "homepage_url": "https://www.presstv.ir/",
     "feed_url": "https://www.presstv.ir/rss.xml", "api_kind": None,
     "fetch_method": "rss", "region": "IR", "languages": ["en"],
     "categories": ["general", "world", "politics"], "bot_sensitivity": 0},

    # ── Middle East: Iraq ────────────────────────────────────────────────────
    {"name": "Iraqi News (EN)", "homepage_url": "https://www.iraqinews.com/",
     "feed_url": "https://www.iraqinews.com/feed/", "api_kind": None,
     "fetch_method": "rss", "region": "IQ", "languages": ["en"],
     "categories": ["general", "world", "politics"], "bot_sensitivity": 0},

    # ── Middle East: Turkey (Turkish & English) ──────────────────────────────
    {"name": "Anadolu Agency (Turkey, EN)", "homepage_url": "https://www.aa.com.tr/en",
     "feed_url": "https://www.aa.com.tr/en/rss/default?cat=guncel", "api_kind": None,
     "fetch_method": "rss", "region": "TR", "languages": ["en"],
     "categories": ["general", "world", "politics"], "bot_sensitivity": 0},
    {"name": "Sabah (Turkey, TR)", "homepage_url": "https://www.sabah.com.tr/",
     "feed_url": "https://www.sabah.com.tr/rss/anasayfa.xml", "api_kind": None,
     "fetch_method": "rss", "region": "TR", "languages": ["tr"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Cumhuriyet (Turkey, TR)", "homepage_url": "https://www.cumhuriyet.com.tr/",
     "feed_url": "https://www.cumhuriyet.com.tr/rss/son_dakika.xml", "api_kind": None,
     "fetch_method": "rss", "region": "TR", "languages": ["tr"],
     "categories": ["general", "politics"], "bot_sensitivity": 0},
    {"name": "Milliyet (Turkey, TR)", "homepage_url": "https://www.milliyet.com.tr/",
     "feed_url": "https://www.milliyet.com.tr/rss/rssNew/sondakikarss.xml", "api_kind": None,
     "fetch_method": "rss", "region": "TR", "languages": ["tr"],
     "categories": ["general", "world"], "bot_sensitivity": 0},
    {"name": "Hürriyet — Ekonomi (Turkey, TR)", "homepage_url": "https://www.hurriyet.com.tr/ekonomi/",
     "feed_url": "https://www.hurriyet.com.tr/rss/ekonomi", "api_kind": None,
     "fetch_method": "rss", "region": "TR", "languages": ["tr"],
     "categories": ["economy", "business", "markets"], "bot_sensitivity": 0},

    # ── Energy / commodities (global, ME/Africa-relevant) ────────────────────
    {"name": "Rigzone (oil & gas)", "homepage_url": "https://www.rigzone.com/",
     "feed_url": "https://www.rigzone.com/news/rss/rigzone_latest.aspx", "api_kind": None,
     "fetch_method": "rss", "region": "GLOBAL", "languages": ["en"],
     "categories": ["energy", "commodities", "business", "niche"], "bot_sensitivity": 0},
    {"name": "ESI Africa (power/energy)", "homepage_url": "https://www.esi-africa.com/",
     "feed_url": None, "api_kind": None,
     "fetch_method": "html", "region": "AF", "languages": ["en"],
     "categories": ["energy", "business", "niche"], "bot_sensitivity": 0},
]
