"""Extra seed bucket — UK / IRELAND / CANADA / AUSTRALIA / NZ LOCAL depth.

Hand-curated, individually live-verified feeds for the long tail of
English-speaking-Commonwealth local and regional journalism: UK regional
dailies (the Reach plc "Live" network and the Iconic/JPI titles), BBC English
region / national-region desks, Irish metro and national-broadcaster feeds,
the Canadian Postmedia chain plus CBC's provincial/metro webfeeds and Global
News, and Australian / New Zealand metros, public-broadcaster state desks and
independent newsrooms (Crikey, Michael West, The Conversation, The Spinoff,
Newsroom, RNZ, ODT). National flagships assumed covered elsewhere (BBC News
national, The Guardian, RTE flagship aside, etc.) are not the focus here; this
bucket is metro / regional / specialist.

Outlets discarded on the verification date because they Cloudflare-challenged,
403'd, 404'd or served HTML-only: Newsquest Scotland (Herald Scotland, The
Courier, Press & Journal), the Irish Examiner feed paths, news.com.au (News
Corp AU bot wall), Toronto Star (rate-limited / search-RSS gone), CTV News
(JS-only), Montreal Gazette /feed/ (HTML wrapper — kept as html fallback),
NZ Herald arc outboundfeeds, BusinessDesk NZ and The Saturday Paper.

Every ``rss`` entry below was fetched with a desktop browser User-Agent on
2026-06-03 and confirmed to return a parseable feed (<rss/<feed/<rdf) with at
least one real <item/<entry.

Shape matches ``newskoo.sources.schemas.SourceCreate``: name, homepage_url,
feed_url, api_kind, fetch_method, region, languages, categories, bot_sensitivity.
"""

from __future__ import annotations

SOURCES: list[dict] = [
    # ── UK — England regional dailies (Reach plc "Live" network) ──────────────
    {"name": "Manchester Evening News", "homepage_url": "https://www.manchestereveningnews.co.uk/", "feed_url": "https://www.manchestereveningnews.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Birmingham Live", "homepage_url": "https://www.birminghammail.co.uk/", "feed_url": "https://www.birminghammail.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Liverpool Echo", "homepage_url": "https://www.liverpoolecho.co.uk/", "feed_url": "https://www.liverpoolecho.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "ChronicleLive (Newcastle)", "homepage_url": "https://www.chroniclelive.co.uk/", "feed_url": "https://www.chroniclelive.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Bristol Post / Bristol Live", "homepage_url": "https://www.bristolpost.co.uk/", "feed_url": "https://www.bristolpost.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Nottinghamshire Live", "homepage_url": "https://www.nottinghampost.com/", "feed_url": "https://www.nottinghampost.com/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Leicestershire Live", "homepage_url": "https://www.leicestermercury.co.uk/", "feed_url": "https://www.leicestermercury.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Teesside Live (Gazette)", "homepage_url": "https://www.gazettelive.co.uk/", "feed_url": "https://www.gazettelive.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Cambridgeshire Live", "homepage_url": "https://www.cambridge-news.co.uk/", "feed_url": "https://www.cambridge-news.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Hull Live (Hull Daily Mail)", "homepage_url": "https://www.hulldailymail.co.uk/", "feed_url": "https://www.hulldailymail.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Devon Live", "homepage_url": "https://www.devonlive.com/", "feed_url": "https://www.devonlive.com/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Cornwall Live", "homepage_url": "https://www.cornwalllive.com/", "feed_url": "https://www.cornwalllive.com/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    # ── UK — Yorkshire / Scotland / Wales titles ─────────────────────────────
    {"name": "Yorkshire Post", "homepage_url": "https://www.yorkshirepost.co.uk/", "feed_url": "https://www.yorkshirepost.co.uk/news/rss", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Scotsman", "homepage_url": "https://www.scotsman.com/", "feed_url": "https://www.scotsman.com/news/rss", "api_kind": None, "fetch_method": "rss", "region": "GB-SCT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Daily Record (Scotland)", "homepage_url": "https://www.dailyrecord.co.uk/", "feed_url": "https://www.dailyrecord.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-SCT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Glasgow Live", "homepage_url": "https://www.glasgowlive.co.uk/", "feed_url": "https://www.glasgowlive.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-SCT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Edinburgh Live", "homepage_url": "https://www.edinburghlive.co.uk/", "feed_url": "https://www.edinburghlive.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-SCT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "WalesOnline", "homepage_url": "https://www.walesonline.co.uk/", "feed_url": "https://www.walesonline.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-WLS", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    # ── UK / NI — Belfast & Northern Ireland ─────────────────────────────────
    {"name": "Belfast Telegraph", "homepage_url": "https://www.belfasttelegraph.co.uk/", "feed_url": "https://www.belfasttelegraph.co.uk/news/rss/", "api_kind": None, "fetch_method": "rss", "region": "GB-NIR", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Belfast Live", "homepage_url": "https://www.belfastlive.co.uk/", "feed_url": "https://www.belfastlive.co.uk/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "GB-NIR", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    # ── UK — BBC English region & national-region desks ──────────────────────
    {"name": "BBC News — Manchester", "homepage_url": "https://www.bbc.co.uk/news/england/manchester", "feed_url": "https://feeds.bbci.co.uk/news/england/manchester/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — London", "homepage_url": "https://www.bbc.co.uk/news/england/london", "feed_url": "https://feeds.bbci.co.uk/news/england/london/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Birmingham & Black Country", "homepage_url": "https://www.bbc.co.uk/news/england/birmingham_and_black_country", "feed_url": "https://feeds.bbci.co.uk/news/england/birmingham_and_black_country/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Merseyside", "homepage_url": "https://www.bbc.co.uk/news/england/merseyside", "feed_url": "https://feeds.bbci.co.uk/news/england/merseyside/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Bristol", "homepage_url": "https://www.bbc.co.uk/news/england/bristol", "feed_url": "https://feeds.bbci.co.uk/news/england/bristol/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Nottingham", "homepage_url": "https://www.bbc.co.uk/news/england/nottingham", "feed_url": "https://feeds.bbci.co.uk/news/england/nottingham/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Cornwall", "homepage_url": "https://www.bbc.co.uk/news/england/cornwall", "feed_url": "https://feeds.bbci.co.uk/news/england/cornwall/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Devon", "homepage_url": "https://www.bbc.co.uk/news/england/devon", "feed_url": "https://feeds.bbci.co.uk/news/england/devon/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-ENG", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Scotland", "homepage_url": "https://www.bbc.co.uk/news/scotland", "feed_url": "https://feeds.bbci.co.uk/news/scotland/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-SCT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Glasgow & West Scotland", "homepage_url": "https://www.bbc.co.uk/news/scotland/glasgow_and_west", "feed_url": "https://feeds.bbci.co.uk/news/scotland/glasgow_and_west/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-SCT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Edinburgh, East & Fife", "homepage_url": "https://www.bbc.co.uk/news/scotland/edinburgh_east_and_fife", "feed_url": "https://feeds.bbci.co.uk/news/scotland/edinburgh_east_and_fife/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-SCT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Wales", "homepage_url": "https://www.bbc.co.uk/news/wales", "feed_url": "https://feeds.bbci.co.uk/news/wales/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-WLS", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "BBC News — Wales Politics", "homepage_url": "https://www.bbc.co.uk/news/wales/wales_politics", "feed_url": "https://feeds.bbci.co.uk/news/wales/wales_politics/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-WLS", "languages": ["en"], "categories": ["local", "politics"], "bot_sensitivity": 0},
    {"name": "BBC News — Northern Ireland", "homepage_url": "https://www.bbc.co.uk/news/northern_ireland", "feed_url": "https://feeds.bbci.co.uk/news/northern_ireland/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "GB-NIR", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    # ── UK — academic / explanatory ──────────────────────────────────────────
    {"name": "The Conversation (UK)", "homepage_url": "https://theconversation.com/uk", "feed_url": "https://theconversation.com/uk/articles.atom", "api_kind": None, "fetch_method": "rss", "region": "GB", "languages": ["en"], "categories": ["analysis", "academia"], "bot_sensitivity": 0},
    # ── Ireland ──────────────────────────────────────────────────────────────
    {"name": "TheJournal.ie", "homepage_url": "https://www.thejournal.ie/", "feed_url": "https://www.thejournal.ie/feed/", "api_kind": None, "fetch_method": "rss", "region": "IE", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Irish Mirror", "homepage_url": "https://www.irishmirror.ie/", "feed_url": "https://www.irishmirror.ie/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "IE", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Dublin Live", "homepage_url": "https://www.dublinlive.ie/", "feed_url": "https://www.dublinlive.ie/news/?service=rss", "api_kind": None, "fetch_method": "rss", "region": "IE", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "RTE News", "homepage_url": "https://www.rte.ie/news/", "feed_url": "https://www.rte.ie/feeds/rss/?index=/news/", "api_kind": None, "fetch_method": "rss", "region": "IE", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "Extra.ie", "homepage_url": "https://extra.ie/", "feed_url": "https://extra.ie/feed", "api_kind": None, "fetch_method": "rss", "region": "IE", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Irish Times (News)", "homepage_url": "https://www.irishtimes.com/", "feed_url": "https://www.irishtimes.com/cmlink/news-1.1319192", "api_kind": None, "fetch_method": "rss", "region": "IE", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    # ── Canada — Postmedia regional dailies ──────────────────────────────────
    {"name": "National Post", "homepage_url": "https://nationalpost.com/", "feed_url": "https://nationalpost.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA", "languages": ["en"], "categories": ["news"], "bot_sensitivity": 1},
    {"name": "Vancouver Sun", "homepage_url": "https://vancouversun.com/", "feed_url": "https://vancouversun.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-BC", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Province (Vancouver)", "homepage_url": "https://theprovince.com/", "feed_url": "https://theprovince.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-BC", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Ottawa Citizen", "homepage_url": "https://ottawacitizen.com/", "feed_url": "https://ottawacitizen.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-ON", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Windsor Star", "homepage_url": "https://windsorstar.com/", "feed_url": "https://windsorstar.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-ON", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Calgary Herald", "homepage_url": "https://calgaryherald.com/", "feed_url": "https://calgaryherald.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-AB", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Edmonton Journal", "homepage_url": "https://edmontonjournal.com/", "feed_url": "https://edmontonjournal.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-AB", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Regina Leader-Post", "homepage_url": "https://leaderpost.com/", "feed_url": "https://leaderpost.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-SK", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Saskatoon StarPhoenix", "homepage_url": "https://thestarphoenix.com/", "feed_url": "https://thestarphoenix.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA-SK", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Montreal Gazette", "homepage_url": "https://montrealgazette.com/", "feed_url": None, "api_kind": None, "fetch_method": "html", "region": "CA-QC", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 2},
    # ── Canada — CBC provincial / metro webfeeds + Global News ────────────────
    {"name": "Global News (Canada)", "homepage_url": "https://globalnews.ca/", "feed_url": "https://globalnews.ca/feed/", "api_kind": None, "fetch_method": "rss", "region": "CA", "languages": ["en"], "categories": ["news"], "bot_sensitivity": 1},
    {"name": "CBC News — Canada", "homepage_url": "https://www.cbc.ca/news/canada", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada", "api_kind": None, "fetch_method": "rss", "region": "CA", "languages": ["en"], "categories": ["news"], "bot_sensitivity": 0},
    {"name": "CBC News — British Columbia", "homepage_url": "https://www.cbc.ca/news/canada/british-columbia", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-britishcolumbia", "api_kind": None, "fetch_method": "rss", "region": "CA-BC", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Toronto", "homepage_url": "https://www.cbc.ca/news/canada/toronto", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-toronto", "api_kind": None, "fetch_method": "rss", "region": "CA-ON", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Ottawa", "homepage_url": "https://www.cbc.ca/news/canada/ottawa", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-ottawa", "api_kind": None, "fetch_method": "rss", "region": "CA-ON", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Montreal", "homepage_url": "https://www.cbc.ca/news/canada/montreal", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-montreal", "api_kind": None, "fetch_method": "rss", "region": "CA-QC", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Calgary", "homepage_url": "https://www.cbc.ca/news/canada/calgary", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-calgary", "api_kind": None, "fetch_method": "rss", "region": "CA-AB", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Edmonton", "homepage_url": "https://www.cbc.ca/news/canada/edmonton", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-edmonton", "api_kind": None, "fetch_method": "rss", "region": "CA-AB", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Saskatchewan", "homepage_url": "https://www.cbc.ca/news/canada/saskatchewan", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-saskatchewan", "api_kind": None, "fetch_method": "rss", "region": "CA-SK", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Manitoba", "homepage_url": "https://www.cbc.ca/news/canada/manitoba", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-manitoba", "api_kind": None, "fetch_method": "rss", "region": "CA-MB", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Nova Scotia", "homepage_url": "https://www.cbc.ca/news/canada/nova-scotia", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-novascotia", "api_kind": None, "fetch_method": "rss", "region": "CA-NS", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — New Brunswick", "homepage_url": "https://www.cbc.ca/news/canada/new-brunswick", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-newbrunswick", "api_kind": None, "fetch_method": "rss", "region": "CA-NB", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Newfoundland & Labrador", "homepage_url": "https://www.cbc.ca/news/canada/newfoundland-labrador", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-newfoundland", "api_kind": None, "fetch_method": "rss", "region": "CA-NL", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "CBC News — Prince Edward Island", "homepage_url": "https://www.cbc.ca/news/canada/prince-edward-island", "feed_url": "https://www.cbc.ca/webfeed/rss/rss-canada-pei", "api_kind": None, "fetch_method": "rss", "region": "CA-PE", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    # ── Australia — Nine metros, public broadcaster, independents ─────────────
    {"name": "Brisbane Times", "homepage_url": "https://www.brisbanetimes.com.au/", "feed_url": "https://www.brisbanetimes.com.au/rss/feed.xml", "api_kind": None, "fetch_method": "rss", "region": "AU-QLD", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "WAtoday (Perth)", "homepage_url": "https://www.watoday.com.au/", "feed_url": "https://www.watoday.com.au/rss/feed.xml", "api_kind": None, "fetch_method": "rss", "region": "AU-WA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Age (Melbourne)", "homepage_url": "https://www.theage.com.au/", "feed_url": "https://www.theage.com.au/rss/feed.xml", "api_kind": None, "fetch_method": "rss", "region": "AU-VIC", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Sydney Morning Herald", "homepage_url": "https://www.smh.com.au/", "feed_url": "https://www.smh.com.au/rss/feed.xml", "api_kind": None, "fetch_method": "rss", "region": "AU-NSW", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Canberra Times", "homepage_url": "https://www.canberratimes.com.au/", "feed_url": "https://www.canberratimes.com.au/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "AU-ACT", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "ABC News (Australia) — Just In", "homepage_url": "https://www.abc.net.au/news/", "feed_url": "https://www.abc.net.au/news/feed/51120/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "AU", "languages": ["en"], "categories": ["news"], "bot_sensitivity": 0},
    {"name": "ABC News (Australia) — Top Stories", "homepage_url": "https://www.abc.net.au/news/", "feed_url": "https://www.abc.net.au/news/feed/45910/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "AU", "languages": ["en"], "categories": ["news"], "bot_sensitivity": 0},
    {"name": "Crikey", "homepage_url": "https://www.crikey.com.au/", "feed_url": "https://www.crikey.com.au/feed/", "api_kind": None, "fetch_method": "rss", "region": "AU", "languages": ["en"], "categories": ["analysis", "politics"], "bot_sensitivity": 1},
    {"name": "Michael West Media", "homepage_url": "https://michaelwest.com.au/", "feed_url": "https://michaelwest.com.au/feed/", "api_kind": None, "fetch_method": "rss", "region": "AU", "languages": ["en"], "categories": ["investigative", "business"], "bot_sensitivity": 1},
    {"name": "The Conversation (Australia)", "homepage_url": "https://theconversation.com/au", "feed_url": "https://theconversation.com/au/articles.atom", "api_kind": None, "fetch_method": "rss", "region": "AU", "languages": ["en"], "categories": ["analysis", "academia"], "bot_sensitivity": 0},
    {"name": "The Conversation (Australia, Business)", "homepage_url": "https://theconversation.com/au/business", "feed_url": "https://theconversation.com/au/business/articles.atom", "api_kind": None, "fetch_method": "rss", "region": "AU", "languages": ["en"], "categories": ["analysis", "business"], "bot_sensitivity": 0},
    # ── New Zealand ──────────────────────────────────────────────────────────
    {"name": "Stuff (New Zealand)", "homepage_url": "https://www.stuff.co.nz/", "feed_url": "https://www.stuff.co.nz/rss", "api_kind": None, "fetch_method": "rss", "region": "NZ", "languages": ["en"], "categories": ["news"], "bot_sensitivity": 1},
    {"name": "The Spinoff", "homepage_url": "https://thespinoff.co.nz/", "feed_url": "https://thespinoff.co.nz/feed", "api_kind": None, "fetch_method": "rss", "region": "NZ", "languages": ["en"], "categories": ["analysis", "culture"], "bot_sensitivity": 0},
    {"name": "Newsroom (New Zealand)", "homepage_url": "https://newsroom.co.nz/", "feed_url": "https://newsroom.co.nz/feed/", "api_kind": None, "fetch_method": "rss", "region": "NZ", "languages": ["en"], "categories": ["news", "analysis"], "bot_sensitivity": 0},
    {"name": "RNZ — National Headlines", "homepage_url": "https://www.rnz.co.nz/", "feed_url": "https://www.rnz.co.nz/rss/national.xml", "api_kind": None, "fetch_method": "rss", "region": "NZ", "languages": ["en"], "categories": ["news"], "bot_sensitivity": 0},
    {"name": "Otago Daily Times", "homepage_url": "https://www.odt.co.nz/", "feed_url": "https://www.odt.co.nz/rss.xml", "api_kind": None, "fetch_method": "rss", "region": "NZ", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 0},
    {"name": "The Conversation (New Zealand)", "homepage_url": "https://theconversation.com/nz", "feed_url": "https://theconversation.com/nz/articles.atom", "api_kind": None, "fetch_method": "rss", "region": "NZ", "languages": ["en"], "categories": ["analysis", "academia"], "bot_sensitivity": 0},
]
