"""Asia local/regional & specialist news sources (long-tail, NOT national flagships).

Live-verified RSS feeds across Indonesia, Philippines, Vietnam, Thailand, Malaysia,
Japan (regional/specialist), Korea (specialist), Singapore, Taiwan, and South Asia
(Pakistan, Bangladesh, Sri Lanka, Nepal) plus Cambodia/Mongolia. Each feed below was
fetched with a browser UA and confirmed to return a parseable RSS/Atom document with
>=1 item at verification time. Majors already covered elsewhere (Yonhap, BBC, etc.)
are intentionally excluded.

Each entry conforms to the standard source schema:
{name, homepage_url, feed_url, api_kind, fetch_method, region, languages,
 categories, bot_sensitivity}
"""

SOURCES: list[dict] = [
    # ---------------- Indonesia ----------------
    {
        "name": "Antara News (terkini)",
        "homepage_url": "https://www.antaranews.com",
        "feed_url": "https://www.antaranews.com/rss/terkini.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "ID",
        "languages": ["id"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Antara News English",
        "homepage_url": "https://en.antaranews.com",
        "feed_url": "https://en.antaranews.com/rss/news.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "ID",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Tempo (Nasional)",
        "homepage_url": "https://www.tempo.co",
        "feed_url": "https://rss.tempo.co/nasional",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "ID",
        "languages": ["id"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Republika",
        "homepage_url": "https://www.republika.co.id",
        "feed_url": "https://www.republika.co.id/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "ID",
        "languages": ["id"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "CNN Indonesia (Nasional)",
        "homepage_url": "https://www.cnnindonesia.com",
        "feed_url": "https://www.cnnindonesia.com/nasional/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "ID",
        "languages": ["id"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Warta Kota (Tribun, Jakarta)",
        "homepage_url": "https://wartakota.tribunnews.com",
        "feed_url": "https://wartakota.tribunnews.com/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "ID",
        "languages": ["id"],
        "categories": ["local", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Coconuts (SE Asia city desks)",
        "homepage_url": "https://coconuts.co",
        "feed_url": "https://coconuts.co/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "ID",
        "languages": ["en"],
        "categories": ["local", "lifestyle"],
        "bot_sensitivity": 1,
    },

    # ---------------- Philippines ----------------
    {
        "name": "BusinessMirror",
        "homepage_url": "https://businessmirror.com.ph",
        "feed_url": "https://businessmirror.com.ph/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PH",
        "languages": ["en"],
        "categories": ["business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "BusinessWorld",
        "homepage_url": "https://www.bworldonline.com",
        "feed_url": "https://www.bworldonline.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PH",
        "languages": ["en"],
        "categories": ["business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "BusinessWorld (Economy)",
        "homepage_url": "https://www.bworldonline.com/economy/",
        "feed_url": "https://www.bworldonline.com/economy/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PH",
        "languages": ["en"],
        "categories": ["business", "economy"],
        "bot_sensitivity": 1,
    },
    {
        "name": "PhilStar (Headlines)",
        "homepage_url": "https://www.philstar.com",
        "feed_url": "https://www.philstar.com/rss/headlines",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PH",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Rappler",
        "homepage_url": "https://www.rappler.com",
        "feed_url": "https://www.rappler.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PH",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Inquirer (NewsInfo)",
        "homepage_url": "https://newsinfo.inquirer.net",
        "feed_url": "https://newsinfo.inquirer.net/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PH",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "MindaNews (Mindanao)",
        "homepage_url": "https://mindanews.com",
        "feed_url": "https://mindanews.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PH",
        "languages": ["en"],
        "categories": ["local", "regional"],
        "bot_sensitivity": 1,
    },

    # ---------------- Vietnam ----------------
    {
        "name": "VietNamNet (Thoi su)",
        "homepage_url": "https://vietnamnet.vn",
        "feed_url": "https://vietnamnet.vn/rss/thoi-su.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VN",
        "languages": ["vi"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "VietNamNet (Cong nghe)",
        "homepage_url": "https://vietnamnet.vn",
        "feed_url": "https://vietnamnet.vn/rss/cong-nghe.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VN",
        "languages": ["vi"],
        "categories": ["technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Nguoi Lao Dong",
        "homepage_url": "https://nld.com.vn",
        "feed_url": "https://nld.com.vn/rss/home.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VN",
        "languages": ["vi"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Nguoi Lao Dong (Kinh te)",
        "homepage_url": "https://nld.com.vn",
        "feed_url": "https://nld.com.vn/rss/kinh-te.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VN",
        "languages": ["vi"],
        "categories": ["business", "economy"],
        "bot_sensitivity": 1,
    },
    {
        "name": "VnExpress International",
        "homepage_url": "https://e.vnexpress.net",
        "feed_url": "https://e.vnexpress.net/rss/news.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VN",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ---------------- Thailand ----------------
    {
        "name": "Khaosod English",
        "homepage_url": "https://www.khaosodenglish.com",
        "feed_url": "https://www.khaosodenglish.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TH",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Matichon (News)",
        "homepage_url": "https://www.matichon.co.th",
        "feed_url": "https://www.matichon.co.th/news/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TH",
        "languages": ["th"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Bangkok Post (Most Recent)",
        "homepage_url": "https://www.bangkokpost.com",
        "feed_url": "https://www.bangkokpost.com/rss/data/most-recent.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TH",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Thaiger",
        "homepage_url": "https://thethaiger.com",
        "feed_url": "https://thethaiger.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TH",
        "languages": ["en"],
        "categories": ["general", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Pattaya Mail",
        "homepage_url": "https://www.pattayamail.com",
        "feed_url": "https://www.pattayamail.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TH",
        "languages": ["en"],
        "categories": ["local", "regional"],
        "bot_sensitivity": 1,
    },

    # ---------------- Malaysia ----------------
    {
        "name": "Malaysiakini (News, EN)",
        "homepage_url": "https://www.malaysiakini.com",
        "feed_url": "https://www.malaysiakini.com/rss/en/news.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MY",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Free Malaysia Today",
        "homepage_url": "https://www.freemalaysiatoday.com",
        "feed_url": "https://www.freemalaysiatoday.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MY",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "New Straits Times",
        "homepage_url": "https://www.nst.com.my",
        "feed_url": "https://www.nst.com.my/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MY",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },

    # ---------------- Singapore ----------------
    {
        "name": "The Straits Times (Singapore)",
        "homepage_url": "https://www.straitstimes.com",
        "feed_url": "https://www.straitstimes.com/news/singapore/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "SG",
        "languages": ["en"],
        "categories": ["local", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Channel NewsAsia (Singapore)",
        "homepage_url": "https://www.channelnewsasia.com",
        "feed_url": "https://www.channelnewsasia.com/rssfeeds/8395986",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "SG",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ---------------- Japan (regional / specialist) ----------------
    {
        "name": "NHK News (Society / cat1)",
        "homepage_url": "https://www3.nhk.or.jp",
        "feed_url": "https://www3.nhk.or.jp/rss/news/cat1.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["general", "society"],
        "bot_sensitivity": 1,
    },
    {
        "name": "NHK News (Business / cat6)",
        "homepage_url": "https://www3.nhk.or.jp",
        "feed_url": "https://www3.nhk.or.jp/rss/news/cat6.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["business", "economy"],
        "bot_sensitivity": 1,
    },
    {
        "name": "NHK News (Science/Culture / cat3)",
        "homepage_url": "https://www3.nhk.or.jp",
        "feed_url": "https://www3.nhk.or.jp/rss/news/cat3.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["science", "culture"],
        "bot_sensitivity": 1,
    },
    {
        "name": "NHK News (Politics / cat4)",
        "homepage_url": "https://www3.nhk.or.jp",
        "feed_url": "https://www3.nhk.or.jp/rss/news/cat4.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Mainichi (Flash)",
        "homepage_url": "https://mainichi.jp",
        "feed_url": "https://mainichi.jp/rss/etc/mainichi-flash.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "ITmedia (All)",
        "homepage_url": "https://www.itmedia.co.jp",
        "feed_url": "https://rss.itmedia.co.jp/rss/2.0/itmedia_all.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "ITmedia (News Bursts)",
        "homepage_url": "https://www.itmedia.co.jp/news/",
        "feed_url": "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "ITmedia (@IT, developer)",
        "homepage_url": "https://atmarkit.itmedia.co.jp",
        "feed_url": "https://rss.itmedia.co.jp/rss/2.0/ait.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JP",
        "languages": ["ja"],
        "categories": ["technology"],
        "bot_sensitivity": 1,
    },

    # ---------------- Korea (specialist) ----------------
    {
        "name": "Korea JoongAng Daily",
        "homepage_url": "https://koreajoongangdaily.joins.com",
        "feed_url": "https://koreajoongangdaily.joins.com/xmls/joins",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "KR",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "KBS World Radio (English)",
        "homepage_url": "https://world.kbs.co.kr",
        "feed_url": "https://world.kbs.co.kr/rss/rss_news.htm?lang=e",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "KR",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Hankyoreh (English)",
        "homepage_url": "https://english.hani.co.kr",
        "feed_url": "https://english.hani.co.kr/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "KR",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Korea Times (World)",
        "homepage_url": "https://www.koreatimes.co.kr",
        "feed_url": "https://www.koreatimes.co.kr/www/rss/world.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "KR",
        "languages": ["en"],
        "categories": ["world"],
        "bot_sensitivity": 1,
    },

    # ---------------- Taiwan ----------------
    {
        "name": "Taipei Times",
        "homepage_url": "https://www.taipeitimes.com",
        "feed_url": "https://www.taipeitimes.com/xml/index.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TW",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "GNN Gamer (Taiwan tech/games)",
        "homepage_url": "https://gnn.gamer.com.tw",
        "feed_url": "https://gnn.gamer.com.tw/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TW",
        "languages": ["zh"],
        "categories": ["technology", "gaming"],
        "bot_sensitivity": 1,
    },

    # ---------------- Hong Kong ----------------
    {
        "name": "South China Morning Post (Hong Kong)",
        "homepage_url": "https://www.scmp.com",
        "feed_url": "https://www.scmp.com/rss/91/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "HK",
        "languages": ["en"],
        "categories": ["local", "national"],
        "bot_sensitivity": 1,
    },

    # ---------------- Pakistan ----------------
    {
        "name": "Dawn",
        "homepage_url": "https://www.dawn.com",
        "feed_url": "https://www.dawn.com/feeds/home",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PK",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The News International",
        "homepage_url": "https://www.thenews.com.pk",
        "feed_url": "https://www.thenews.com.pk/rss/1/1",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PK",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Express Tribune (Pakistan)",
        "homepage_url": "https://tribune.com.pk",
        "feed_url": "https://tribune.com.pk/feed/home",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PK",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Geo News (Pakistan)",
        "homepage_url": "https://www.geo.tv",
        "feed_url": "https://www.geo.tv/rss/1/53",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PK",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Business Recorder (Pakistan)",
        "homepage_url": "https://www.brecorder.com",
        "feed_url": "https://www.brecorder.com/feeds/latest-news",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PK",
        "languages": ["en"],
        "categories": ["business", "economy"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Nation (Pakistan, National)",
        "homepage_url": "https://www.nation.com.pk",
        "feed_url": "https://www.nation.com.pk/rss/national",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PK",
        "languages": ["en"],
        "categories": ["national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Daily Pakistan (English)",
        "homepage_url": "https://en.dailypakistan.com.pk",
        "feed_url": "https://en.dailypakistan.com.pk/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PK",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ---------------- Bangladesh ----------------
    {
        "name": "The Daily Star (Bangladesh)",
        "homepage_url": "https://www.thedailystar.net",
        "feed_url": "https://www.thedailystar.net/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BD",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Prothom Alo",
        "homepage_url": "https://www.prothomalo.com",
        "feed_url": "https://www.prothomalo.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BD",
        "languages": ["bn"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Daily Observer (Bangladesh)",
        "homepage_url": "https://www.observerbd.com",
        "feed_url": "https://www.observerbd.com/rss.php",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BD",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ---------------- Sri Lanka ----------------
    {
        "name": "The Island (Sri Lanka)",
        "homepage_url": "https://www.island.lk",
        "feed_url": "https://www.island.lk/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "LK",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },

    # ---------------- Nepal ----------------
    {
        "name": "The Kathmandu Post",
        "homepage_url": "https://kathmandupost.com",
        "feed_url": "https://kathmandupost.com/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "NP",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Online Khabar (English)",
        "homepage_url": "https://english.onlinekhabar.com",
        "feed_url": "https://english.onlinekhabar.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "NP",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ---------------- India (regional / non-flagship) ----------------
    {
        "name": "The New Indian Express",
        "homepage_url": "https://www.newindianexpress.com",
        "feed_url": "https://www.newindianexpress.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },

    # ---------------- Cambodia ----------------
    {
        "name": "Khmer Times",
        "homepage_url": "https://www.khmertimeskh.com",
        "feed_url": "https://www.khmertimeskh.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "KH",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },

    # ---------------- Mongolia ----------------
    {
        "name": "News.mn (English)",
        "homepage_url": "https://news.mn/en/",
        "feed_url": "https://news.mn/en/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MN",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
]
