"""India language & state press — long-tail regional/language-native outlets.

Live-verified RSS/Atom feeds covering India's major language presses (Hindi, Tamil,
Telugu, Bengali, Marathi, Kannada, Malayalam, Gujarati, Odia) and state/city desks,
plus regional English editions and North-East / Kashmir / Goa / Odisha papers. These
are deliberately long-tail: state editions, language-native digital outlets, regional
broadcasters' news desks and city desks — NOT the national English flagships (TOI's
national edition, ToI national, etc. are excluded; only city/state TOI desks are kept).

Each feed below was fetched with a desktop browser User-Agent and confirmed to return a
parseable RSS/Atom document containing >=1 <item>/<entry> at verification time. Many of
these outlets are bot-sensitive (Amar Ujala, OneIndia network, TOI city desks); the
browser UA is required to retrieve them.

Each entry conforms to the standard source schema:
{name, homepage_url, feed_url, api_kind, fetch_method, region, languages,
 categories, bot_sensitivity}
"""

SOURCES: list[dict] = [
    # ==================== HINDI (Amar Ujala state editions) ====================
    {
        "name": "Amar Ujala (Breaking News)",
        "homepage_url": "https://www.amarujala.com",
        "feed_url": "https://www.amarujala.com/rss/breaking-news.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["general", "breaking"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (India)",
        "homepage_url": "https://www.amarujala.com",
        "feed_url": "https://www.amarujala.com/rss/india-news.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["general", "national"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (Uttar Pradesh)",
        "homepage_url": "https://www.amarujala.com/uttar-pradesh",
        "feed_url": "https://www.amarujala.com/rss/uttar-pradesh.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (Bihar)",
        "homepage_url": "https://www.amarujala.com/bihar",
        "feed_url": "https://www.amarujala.com/rss/bihar.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (Madhya Pradesh)",
        "homepage_url": "https://www.amarujala.com/madhya-pradesh",
        "feed_url": "https://www.amarujala.com/rss/madhya-pradesh.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (Rajasthan)",
        "homepage_url": "https://www.amarujala.com/rajasthan",
        "feed_url": "https://www.amarujala.com/rss/rajasthan.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (Haryana)",
        "homepage_url": "https://www.amarujala.com/haryana",
        "feed_url": "https://www.amarujala.com/rss/haryana.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (Himachal Pradesh)",
        "homepage_url": "https://www.amarujala.com/himachal-pradesh",
        "feed_url": "https://www.amarujala.com/rss/himachal-pradesh.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Amar Ujala (Dehradun / Uttarakhand)",
        "homepage_url": "https://www.amarujala.com/dehradun",
        "feed_url": "https://www.amarujala.com/rss/dehradun.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "OneIndia Hindi",
        "homepage_url": "https://hindi.oneindia.com",
        "feed_url": "https://hindi.oneindia.com/rss/hindi-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["hi"],
        "categories": ["general"],
        "bot_sensitivity": 2,
    },

    # ==================== TAMIL ====================
    {
        "name": "Hindu Tamil Thisai",
        "homepage_url": "https://www.hindutamil.in",
        "feed_url": "https://www.hindutamil.in/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["ta"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OneIndia Tamil",
        "homepage_url": "https://tamil.oneindia.com",
        "feed_url": "https://tamil.oneindia.com/rss/tamil-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["ta"],
        "categories": ["general"],
        "bot_sensitivity": 2,
    },
    {
        "name": "OneIndia Tamil (News)",
        "homepage_url": "https://tamil.oneindia.com/news",
        "feed_url": "https://tamil.oneindia.com/rss/feeds/tamil-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["ta"],
        "categories": ["general", "national"],
        "bot_sensitivity": 2,
    },

    # ==================== TELUGU ====================
    {
        "name": "Sakshi (Telugu)",
        "homepage_url": "https://www.sakshi.com",
        "feed_url": "https://www.sakshi.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["te"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Namasthe Telangana (NT News)",
        "homepage_url": "https://www.ntnews.com",
        "feed_url": "https://www.ntnews.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["te"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "TV9 Telugu",
        "homepage_url": "https://www.tv9telugu.com",
        "feed_url": "https://www.tv9telugu.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["te"],
        "categories": ["general", "broadcast"],
        "bot_sensitivity": 1,
    },
    {
        "name": "10TV Telugu",
        "homepage_url": "https://www.10tv.in",
        "feed_url": "https://www.10tv.in/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["te"],
        "categories": ["general", "broadcast"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OneIndia Telugu (News)",
        "homepage_url": "https://telugu.oneindia.com/news",
        "feed_url": "https://telugu.oneindia.com/rss/feeds/telugu-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["te"],
        "categories": ["general", "national"],
        "bot_sensitivity": 2,
    },

    # ==================== BENGALI ====================
    {
        "name": "Sangbad Pratidin",
        "homepage_url": "https://www.sangbadpratidin.in",
        "feed_url": "https://www.sangbadpratidin.in/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["bn"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Uttarbanga Sambad",
        "homepage_url": "https://www.uttarbangasambad.com",
        "feed_url": "https://www.uttarbangasambad.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["bn"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OneIndia Bengali",
        "homepage_url": "https://bengali.oneindia.com",
        "feed_url": "https://bengali.oneindia.com/rss/bengali-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["bn"],
        "categories": ["general"],
        "bot_sensitivity": 2,
    },

    # ==================== MARATHI ====================
    {
        "name": "TV9 Marathi",
        "homepage_url": "https://www.tv9marathi.com",
        "feed_url": "https://www.tv9marathi.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["mr"],
        "categories": ["general", "broadcast"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Max Maharashtra",
        "homepage_url": "https://www.maxmaharashtra.com",
        "feed_url": "https://www.maxmaharashtra.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["mr"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OneIndia Marathi",
        "homepage_url": "https://marathi.oneindia.com",
        "feed_url": "https://marathi.oneindia.com/rss/marathi-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["mr"],
        "categories": ["general"],
        "bot_sensitivity": 2,
    },

    # ==================== KANNADA ====================
    {
        "name": "TV9 Kannada",
        "homepage_url": "https://www.tv9kannada.com",
        "feed_url": "https://www.tv9kannada.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["kn"],
        "categories": ["general", "broadcast"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OneIndia Kannada",
        "homepage_url": "https://kannada.oneindia.com",
        "feed_url": "https://kannada.oneindia.com/rss/kannada-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["kn"],
        "categories": ["general"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Vartha Bharati (English / Karnataka)",
        "homepage_url": "https://english.varthabharati.in",
        "feed_url": "https://english.varthabharati.in/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Star of Mysore",
        "homepage_url": "https://starofmysore.com",
        "feed_url": "https://starofmysore.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 1,
    },

    # ==================== MALAYALAM ====================
    {
        "name": "Onmanorama (Kerala)",
        "homepage_url": "https://www.onmanorama.com",
        "feed_url": "https://www.onmanorama.com/news/kerala.feeds.onmrss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Onmanorama (India)",
        "homepage_url": "https://www.onmanorama.com/news/india.html",
        "feed_url": "https://www.onmanorama.com/news/india.feeds.onmrss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "24 News (Malayalam)",
        "homepage_url": "https://www.twentyfournews.com",
        "feed_url": "https://www.twentyfournews.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["ml"],
        "categories": ["general", "broadcast"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OneIndia Malayalam (News)",
        "homepage_url": "https://malayalam.oneindia.com/news",
        "feed_url": "https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["ml"],
        "categories": ["general", "national"],
        "bot_sensitivity": 2,
    },

    # ==================== GUJARATI ====================
    {
        "name": "Gujarat Samachar (Top Stories)",
        "homepage_url": "https://www.gujaratsamachar.com",
        "feed_url": "https://www.gujaratsamachar.com/rss/top-stories",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["gu"],
        "categories": ["general", "breaking"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Gujarat Samachar (National)",
        "homepage_url": "https://www.gujaratsamachar.com/news/national",
        "feed_url": "https://www.gujaratsamachar.com/rss/category/national",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["gu"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Gujarat Samachar (Sports)",
        "homepage_url": "https://www.gujaratsamachar.com/sports",
        "feed_url": "https://www.gujaratsamachar.com/rss/category/sports",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["gu"],
        "categories": ["sports"],
        "bot_sensitivity": 1,
    },
    {
        "name": "TV9 Gujarati",
        "homepage_url": "https://tv9gujarati.com",
        "feed_url": "https://tv9gujarati.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["gu"],
        "categories": ["general", "broadcast"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OneIndia Gujarati (News)",
        "homepage_url": "https://gujarati.oneindia.com/news",
        "feed_url": "https://gujarati.oneindia.com/rss/feeds/gujarati-news-fb.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["gu"],
        "categories": ["general", "national"],
        "bot_sensitivity": 2,
    },

    # ==================== ODIA / ODISHA ====================
    {
        "name": "Dharitri (Odia)",
        "homepage_url": "https://www.dharitri.com",
        "feed_url": "https://www.dharitri.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["or"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Kalinga TV",
        "homepage_url": "https://kalingatv.com",
        "feed_url": "https://kalingatv.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en", "or"],
        "categories": ["general", "broadcast"],
        "bot_sensitivity": 1,
    },
    {
        "name": "OdishaBytes",
        "homepage_url": "https://www.odishabytes.com",
        "feed_url": "https://www.odishabytes.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Pragativadi (Odisha)",
        "homepage_url": "https://pragativadi.com",
        "feed_url": "https://pragativadi.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Orissa POST",
        "homepage_url": "https://www.orissapost.com",
        "feed_url": "https://www.orissapost.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },

    # ==================== ENGLISH STATE / CITY EDITIONS ====================
    {
        "name": "Telangana Today",
        "homepage_url": "https://telanganatoday.com",
        "feed_url": "https://telanganatoday.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The South First",
        "homepage_url": "https://www.thesouthfirst.com",
        "feed_url": "https://www.thesouthfirst.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Siasat Daily (Hyderabad)",
        "homepage_url": "https://www.siasat.com",
        "feed_url": "https://www.siasat.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "city"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Deccan Chronicle (Southern States)",
        "homepage_url": "https://www.deccanchronicle.com/southern-states",
        "feed_url": "https://www.deccanchronicle.com/rss_feed/southern-states",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Deccan Chronicle (Nation)",
        "homepage_url": "https://www.deccanchronicle.com/nation",
        "feed_url": "https://www.deccanchronicle.com/rss_feed/nation",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "national"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Free Press Journal (Mumbai)",
        "homepage_url": "https://www.freepressjournal.in",
        "feed_url": "https://www.freepressjournal.in/stories.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["general", "city"],
        "bot_sensitivity": 1,
    },

    # ---------- The Hindu state & city desks (long-tail regional feeders) ----------
    {
        "name": "The Hindu — Telangana",
        "homepage_url": "https://www.thehindu.com/news/national/telangana/",
        "feed_url": "https://www.thehindu.com/news/national/telangana/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hindu — Tamil Nadu",
        "homepage_url": "https://www.thehindu.com/news/national/tamil-nadu/",
        "feed_url": "https://www.thehindu.com/news/national/tamil-nadu/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hindu — Kerala",
        "homepage_url": "https://www.thehindu.com/news/national/kerala/",
        "feed_url": "https://www.thehindu.com/news/national/kerala/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hindu — Karnataka",
        "homepage_url": "https://www.thehindu.com/news/national/karnataka/",
        "feed_url": "https://www.thehindu.com/news/national/karnataka/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hindu — Andhra Pradesh",
        "homepage_url": "https://www.thehindu.com/news/national/andhra-pradesh/",
        "feed_url": "https://www.thehindu.com/news/national/andhra-pradesh/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hindu — Hyderabad",
        "homepage_url": "https://www.thehindu.com/news/cities/Hyderabad/",
        "feed_url": "https://www.thehindu.com/news/cities/Hyderabad/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hindu — Bengaluru",
        "homepage_url": "https://www.thehindu.com/news/cities/bangalore/",
        "feed_url": "https://www.thehindu.com/news/cities/bangalore/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hindu — Kochi",
        "homepage_url": "https://www.thehindu.com/news/cities/Kochi/",
        "feed_url": "https://www.thehindu.com/news/cities/Kochi/feeder/default.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 1,
    },

    # ---------- Times of India city desks (long-tail city editions only) ----------
    {
        "name": "Times of India — Hyderabad",
        "homepage_url": "https://timesofindia.indiatimes.com/city/hyderabad",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/-2128816011.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Mumbai",
        "homepage_url": "https://timesofindia.indiatimes.com/city/mumbai",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Bengaluru",
        "homepage_url": "https://timesofindia.indiatimes.com/city/bengaluru",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Pune",
        "homepage_url": "https://timesofindia.indiatimes.com/city/pune",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Chennai",
        "homepage_url": "https://timesofindia.indiatimes.com/city/chennai",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/2950623.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Mangaluru",
        "homepage_url": "https://timesofindia.indiatimes.com/city/mangaluru",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/3942690.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Prayagraj (Allahabad)",
        "homepage_url": "https://timesofindia.indiatimes.com/city/allahabad",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/3947060.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Kanpur",
        "homepage_url": "https://timesofindia.indiatimes.com/city/kanpur",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/3947067.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Rajkot",
        "homepage_url": "https://timesofindia.indiatimes.com/city/rajkot",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/3942663.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },
    {
        "name": "Times of India — Goa",
        "homepage_url": "https://timesofindia.indiatimes.com/city/goa",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/3012535.cms",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "city"],
        "bot_sensitivity": 2,
    },

    # ==================== NORTH-EAST INDIA ====================
    {
        "name": "EastMojo (North-East India)",
        "homepage_url": "https://www.eastmojo.com",
        "feed_url": "https://www.eastmojo.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The News Mill (North-East)",
        "homepage_url": "https://thenewsmill.com",
        "feed_url": "https://thenewsmill.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "NorthEast Now",
        "homepage_url": "https://nenow.in",
        "feed_url": "https://nenow.in/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Northeast Today",
        "homepage_url": "https://thenortheasttoday.com",
        "feed_url": "https://thenortheasttoday.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Assam Tribune",
        "homepage_url": "https://www.assamtribune.com",
        "feed_url": "https://www.assamtribune.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Assam Times",
        "homepage_url": "https://www.assamtimes.org",
        "feed_url": "https://www.assamtimes.org/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Nagaland Post",
        "homepage_url": "https://www.nagalandpost.com",
        "feed_url": "https://www.nagalandpost.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Hills Times (Assam)",
        "homepage_url": "https://www.thehillstimes.in",
        "feed_url": "https://www.thehillstimes.in/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Meghalaya Monitor",
        "homepage_url": "https://www.meghalayamonitor.com",
        "feed_url": "https://www.meghalayamonitor.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },

    # ==================== JAMMU & KASHMIR ====================
    {
        "name": "Kashmir Life",
        "homepage_url": "https://kashmirlife.net",
        "feed_url": "https://kashmirlife.net/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Rising Kashmir",
        "homepage_url": "https://www.risingkashmir.com",
        "feed_url": "https://www.risingkashmir.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Kashmir Observer",
        "homepage_url": "https://kashmirobserver.net",
        "feed_url": "https://kashmirobserver.net/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Kashmir Monitor",
        "homepage_url": "https://thekashmirmonitor.net",
        "feed_url": "https://thekashmirmonitor.net/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },

    # ==================== GOA ====================
    {
        "name": "Goa Chronicle",
        "homepage_url": "https://goachronicle.com",
        "feed_url": "https://goachronicle.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "IN",
        "languages": ["en"],
        "categories": ["regional", "state"],
        "bot_sensitivity": 1,
    },
]
