"""Latin America local / regional news sources (long-tail).

State, provincial, departmental and city outlets across Brazil, Mexico,
Argentina, Colombia, Chile, Peru, Uruguay, Ecuador, Bolivia, Venezuela,
Paraguay, Central America and the Caribbean. Spanish (es) and Portuguese
(pt) native outlets, plus a few English-language Caribbean papers.

Every feed below was live-verified with a browser UA: each returns a
parseable RSS/Atom document with >= 1 item. National flagships and the
obvious majors are intentionally excluded in favour of regional depth.
"""

SOURCES: list[dict] = [
    # ------------------------------------------------------------------
    # BRAZIL (pt) — state / regional
    # ------------------------------------------------------------------
    {
        "name": "Gazeta do Povo (Paraná)",
        "homepage_url": "https://www.gazetadopovo.com.br/",
        "feed_url": "https://www.gazetadopovo.com.br/feed/rss/ultimas-noticias.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR-PR",
        "languages": ["pt"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "A Tarde (Bahia)",
        "homepage_url": "https://atarde.com.br/",
        "feed_url": "https://atarde.com.br/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR-BA",
        "languages": ["pt"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Tribuna de Minas (Juiz de Fora, MG)",
        "homepage_url": "https://www.tribunademinas.com.br/",
        "feed_url": "https://www.tribunademinas.com.br/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR-MG",
        "languages": ["pt"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Folha de Londrina (Paraná)",
        "homepage_url": "https://www.folhadelondrina.com.br/",
        "feed_url": "https://www.folhadelondrina.com.br/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR-PR",
        "languages": ["pt"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Campo Grande News (Mato Grosso do Sul)",
        "homepage_url": "https://www.campograndenews.com.br/",
        "feed_url": "https://www.campograndenews.com.br/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR-MS",
        "languages": ["pt"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Sul21 (Rio Grande do Sul)",
        "homepage_url": "https://www.sul21.com.br/",
        "feed_url": "https://www.sul21.com.br/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR-RS",
        "languages": ["pt"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Massa! (Bahia)",
        "homepage_url": "https://www.massa.com.br/",
        "feed_url": "https://www.massa.com.br/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR-BA",
        "languages": ["pt"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Carta Capital",
        "homepage_url": "https://www.cartacapital.com.br/",
        "feed_url": "https://www.cartacapital.com.br/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR",
        "languages": ["pt"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Diário do Centro do Mundo (DCM)",
        "homepage_url": "https://www.diariodocentrodomundo.com.br/",
        "feed_url": "https://www.diariodocentrodomundo.com.br/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BR",
        "languages": ["pt"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # MEXICO (es) — state / regional
    # ------------------------------------------------------------------
    {
        "name": "El Informador (Guadalajara, Jalisco)",
        "homepage_url": "https://www.informador.mx/",
        "feed_url": "https://www.informador.mx/rss/jalisco.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-JAL",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Informador — Últimas noticias",
        "homepage_url": "https://www.informador.mx/",
        "feed_url": "https://www.informador.mx/rss/ultimas-noticias.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-JAL",
        "languages": ["es"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Vanguardia (Saltillo, Coahuila)",
        "homepage_url": "https://vanguardia.com.mx/",
        "feed_url": "https://vanguardia.com.mx/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-COA",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La Jornada",
        "homepage_url": "https://www.jornada.com.mx/",
        "feed_url": "https://www.jornada.com.mx/rss/edicion.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Periódico AM (León, Guanajuato)",
        "homepage_url": "https://www.am.com.mx/",
        "feed_url": "https://www.am.com.mx/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-GUA",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La Voz de la Frontera (Mexicali, Baja California)",
        "homepage_url": "https://www.lavozdelafrontera.com.mx/",
        "feed_url": "https://www.lavozdelafrontera.com.mx/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-BCN",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Heraldo de Chihuahua",
        "homepage_url": "https://www.elheraldodechihuahua.com.mx/",
        "feed_url": "https://www.elheraldodechihuahua.com.mx/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-CHH",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Tabasco Hoy",
        "homepage_url": "https://www.tabascohoy.com/",
        "feed_url": "https://www.tabascohoy.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-TAB",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Tribuna (Ciudad Obregón, Sonora)",
        "homepage_url": "https://www.tribuna.com.mx/",
        "feed_url": "https://www.tribuna.com.mx/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-SON",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Contramuro (Michoacán)",
        "homepage_url": "https://www.contramuro.com/",
        "feed_url": "https://www.contramuro.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "MX-MIC",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # ARGENTINA (es) — provincial
    # ------------------------------------------------------------------
    {
        "name": "Río Negro (Patagonia)",
        "homepage_url": "https://www.rionegro.com.ar/",
        "feed_url": "https://www.rionegro.com.ar/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "AR-R",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Día (La Plata, Buenos Aires)",
        "homepage_url": "https://www.eldia.com/",
        "feed_url": "https://www.eldia.com/rss/ultimas.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "AR-B",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # COLOMBIA (es) — regional
    # ------------------------------------------------------------------
    {
        "name": "El Colombiano (Medellín, Antioquia)",
        "homepage_url": "https://www.elcolombiano.com/",
        "feed_url": "https://www.elcolombiano.com/rss/portada.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CO-ANT",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La Patria (Manizales, Caldas)",
        "homepage_url": "https://www.lapatria.com/",
        "feed_url": "https://www.lapatria.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CO-CAL",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Diario del Huila (Neiva)",
        "homepage_url": "https://www.diariodelhuila.com/",
        "feed_url": "https://www.diariodelhuila.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CO-HUI",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La República (Colombia, economía)",
        "homepage_url": "https://www.larepublica.co/",
        "feed_url": "https://www.larepublica.co/rss/economia",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CO",
        "languages": ["es"],
        "categories": ["business", "economy"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # CHILE (es) — regional / independent
    # ------------------------------------------------------------------
    {
        "name": "The Clinic (Chile)",
        "homepage_url": "https://www.theclinic.cl/",
        "feed_url": "https://www.theclinic.cl/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CL",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La Nación (Chile)",
        "homepage_url": "https://www.lanacion.cl/",
        "feed_url": "https://www.lanacion.cl/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CL",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La Discusión (Chillán, Ñuble)",
        "homepage_url": "https://www.ladiscusion.cl/",
        "feed_url": "https://www.ladiscusion.cl/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CL-NB",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # PERU (es) — regional
    # ------------------------------------------------------------------
    {
        "name": "El Comercio (Perú)",
        "homepage_url": "https://elcomercio.pe/",
        "feed_url": "https://elcomercio.pe/arcio/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PE",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Gestión (Perú)",
        "homepage_url": "https://gestion.pe/",
        "feed_url": "https://gestion.pe/arcio/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PE",
        "languages": ["es"],
        "categories": ["business", "economy"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Diario Correo (Perú)",
        "homepage_url": "https://diariocorreo.pe/",
        "feed_url": "https://diariocorreo.pe/arcio/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PE",
        "languages": ["es"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Perú21",
        "homepage_url": "https://peru21.pe/",
        "feed_url": "https://peru21.pe/arcio/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PE",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Exitosa Noticias (Perú)",
        "homepage_url": "https://exitosanoticias.pe/",
        "feed_url": "https://exitosanoticias.pe/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PE",
        "languages": ["es"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # URUGUAY (es)
    # ------------------------------------------------------------------
    {
        "name": "Montevideo Portal",
        "homepage_url": "https://www.montevideo.com.uy/",
        "feed_url": "https://www.montevideo.com.uy/anxml.aspx?59",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "UY",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # ECUADOR (es)
    # ------------------------------------------------------------------
    {
        "name": "El Universo (Guayaquil)",
        "homepage_url": "https://www.eluniverso.com/",
        "feed_url": "https://www.eluniverso.com/arc/outboundfeeds/rss/?outputType=xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "EC-G",
        "languages": ["es"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Expreso (Guayaquil)",
        "homepage_url": "https://www.expreso.ec/",
        "feed_url": "https://www.expreso.ec/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "EC-G",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Comercio (Quito)",
        "homepage_url": "https://www.elcomercio.com/",
        "feed_url": "https://www.elcomercio.com/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "EC-P",
        "languages": ["es"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # BOLIVIA (es)
    # ------------------------------------------------------------------
    {
        "name": "Los Tiempos (Cochabamba)",
        "homepage_url": "https://www.lostiempos.com/",
        "feed_url": "https://www.lostiempos.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BO-C",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Opinión (Cochabamba)",
        "homepage_url": "https://www.opinion.com.bo/",
        "feed_url": "https://www.opinion.com.bo/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BO-C",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Eju.tv (Bolivia)",
        "homepage_url": "https://eju.tv/",
        "feed_url": "https://eju.tv/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BO",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # PARAGUAY (es)
    # ------------------------------------------------------------------
    {
        "name": "La Nación (Paraguay)",
        "homepage_url": "https://www.lanacion.com.py/",
        "feed_url": "https://www.lanacion.com.py/arc/outboundfeeds/rss/?outputType=xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PY",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Hoy (Paraguay)",
        "homepage_url": "https://www.hoy.com.py/",
        "feed_url": "https://www.hoy.com.py/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "PY",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # VENEZUELA (es) — independent / regional
    # ------------------------------------------------------------------
    {
        "name": "Efecto Cocuyo",
        "homepage_url": "https://efectococuyo.com/",
        "feed_url": "https://efectococuyo.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "TalCual",
        "homepage_url": "https://talcualdigital.com/",
        "feed_url": "https://talcualdigital.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Nacional (Venezuela)",
        "homepage_url": "https://www.elnacional.com/",
        "feed_url": "https://www.elnacional.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La Patilla",
        "homepage_url": "https://www.lapatilla.com/",
        "feed_url": "https://www.lapatilla.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Runrun.es",
        "homepage_url": "https://runrun.es/",
        "feed_url": "https://runrun.es/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Crónica.Uno (Venezuela)",
        "homepage_url": "https://cronica.uno/",
        "feed_url": "https://cronica.uno/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Impulso (Barquisimeto, Lara)",
        "homepage_url": "https://www.elimpulso.com/",
        "feed_url": "https://www.elimpulso.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE-M",
        "languages": ["es"],
        "categories": ["general", "regional", "local"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Descifrado (Venezuela)",
        "homepage_url": "https://www.descifrado.com/",
        "feed_url": "https://www.descifrado.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Pitazo (Venezuela)",
        "homepage_url": "https://www.elpitazo.net/",
        "feed_url": "https://www.elpitazo.net/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "VE",
        "languages": ["es"],
        "categories": ["general", "regional"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # CENTRAL AMERICA (es)
    # ------------------------------------------------------------------
    {
        "name": "Prensa Libre (Guatemala)",
        "homepage_url": "https://www.prensalibre.com/",
        "feed_url": "https://www.prensalibre.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GT",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "República (Guatemala)",
        "homepage_url": "https://republica.gt/",
        "feed_url": "https://republica.gt/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GT",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Salvador.com (El Diario de Hoy)",
        "homepage_url": "https://www.elsalvador.com/",
        "feed_url": "https://www.elsalvador.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "SV",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Criterio.hn (Honduras)",
        "homepage_url": "https://criterio.hn/",
        "feed_url": "https://criterio.hn/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "HN",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "La Nación (Costa Rica)",
        "homepage_url": "https://www.nacion.com/",
        "feed_url": "https://www.nacion.com/arc/outboundfeeds/rss/?outputType=xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CR",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },

    # ------------------------------------------------------------------
    # CARIBBEAN (es / en)
    # ------------------------------------------------------------------
    {
        "name": "Diario Libre (Rep. Dominicana)",
        "homepage_url": "https://www.diariolibre.com/",
        "feed_url": "https://www.diariolibre.com/rss/portada.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "DO",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "El Nuevo Diario (Rep. Dominicana)",
        "homepage_url": "https://elnuevodiario.com.do/",
        "feed_url": "https://elnuevodiario.com.do/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "DO",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Hoy (Rep. Dominicana)",
        "homepage_url": "https://hoy.com.do/",
        "feed_url": "https://hoy.com.do/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "DO",
        "languages": ["es"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Jamaica Gleaner",
        "homepage_url": "https://jamaica-gleaner.com/",
        "feed_url": "https://jamaica-gleaner.com/feed/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JM",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Jamaica Observer",
        "homepage_url": "https://www.jamaicaobserver.com/",
        "feed_url": "https://www.jamaicaobserver.com/feed/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "JM",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Trinidad & Tobago Newsday",
        "homepage_url": "https://newsday.co.tt/",
        "feed_url": "https://newsday.co.tt/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "TT",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Granma (Cuba)",
        "homepage_url": "https://www.granma.cu/",
        "feed_url": "https://www.granma.cu/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CU",
        "languages": ["es"],
        "categories": ["general", "politics"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Kaieteur News (Guyana)",
        "homepage_url": "https://www.kaieteurnewsonline.com/",
        "feed_url": "https://www.kaieteurnewsonline.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GY",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Nation News (Barbados)",
        "homepage_url": "https://www.nationnews.com/",
        "feed_url": "https://www.nationnews.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BB",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Barbados Today",
        "homepage_url": "https://barbadostoday.bb/",
        "feed_url": "https://barbadostoday.bb/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "BB",
        "languages": ["en"],
        "categories": ["general"],
        "bot_sensitivity": 1,
    },
]
