"""Tech/industry trade-press long-tail feeds (NEW verticals).

Specialist and trade publications across telecoms, cloud/devops, data/AI,
gaming, fintech, retail, healthcare-IT, manufacturing/robotics, EVs/batteries,
clean energy (solar/wind/nuclear/hydrogen/storage), water, construction,
chemicals, packaging, textiles, semiconductors, data centers, and supply chain.

Every feed_url below was live-verified (HTTP 200, parseable <rss>/<feed> with
>=1 <item>/<entry>) with a browser User-Agent. National flagships and obvious
majors are intentionally excluded in favour of trade depth.
"""

SOURCES: list[dict] = [
    # --- Telecoms / networking / wireless ---
    {
        "name": "Light Reading",
        "homepage_url": "https://www.lightreading.com/",
        "feed_url": "https://www.lightreading.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["telecoms", "networking", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Fierce Wireless",
        "homepage_url": "https://www.fiercewireless.com/",
        "feed_url": "https://www.fiercewireless.com/rss/xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["telecoms", "wireless", "5g"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Mobile World Live",
        "homepage_url": "https://www.mobileworldlive.com/",
        "feed_url": "https://www.mobileworldlive.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["telecoms", "mobile", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "RCR Wireless News",
        "homepage_url": "https://www.rcrwireless.com/",
        "feed_url": "https://www.rcrwireless.com/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["telecoms", "wireless", "5g"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Network World",
        "homepage_url": "https://www.networkworld.com/",
        "feed_url": "https://www.networkworld.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["networking", "enterprise-it", "technology"],
        "bot_sensitivity": 1,
    },
    # --- Cloud / devops / data centers ---
    {
        "name": "The New Stack",
        "homepage_url": "https://thenewstack.io/",
        "feed_url": "https://thenewstack.io/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["cloud", "devops", "software"],
        "bot_sensitivity": 1,
    },
    {
        "name": "InfoQ",
        "homepage_url": "https://www.infoq.com/",
        "feed_url": "https://www.infoq.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["software", "architecture", "devops"],
        "bot_sensitivity": 1,
    },
    {
        "name": "DevOps.com",
        "homepage_url": "https://devops.com/",
        "feed_url": "https://devops.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["devops", "cloud", "software"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Data Center Dynamics",
        "homepage_url": "https://www.datacenterdynamics.com/",
        "feed_url": "https://www.datacenterdynamics.com/en/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["data-centers", "infrastructure", "cloud"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Blocks & Files",
        "homepage_url": "https://blocksandfiles.com/",
        "feed_url": "https://blocksandfiles.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["storage", "data-centers", "enterprise-it"],
        "bot_sensitivity": 1,
    },
    {
        "name": "HPCwire",
        "homepage_url": "https://www.hpcwire.com/",
        "feed_url": "https://www.hpcwire.com/feed/",
        "api_kind": None,
        "fetch_method": "html",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["hpc", "supercomputing", "technology"],
        "bot_sensitivity": 2,
    },
    # --- Data / AI ---
    {
        "name": "VentureBeat AI",
        "homepage_url": "https://venturebeat.com/category/ai/",
        "feed_url": "https://venturebeat.com/category/ai/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["ai", "technology", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "MarkTechPost",
        "homepage_url": "https://www.marktechpost.com/",
        "feed_url": "https://www.marktechpost.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["ai", "machine-learning", "research"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Decoder",
        "homepage_url": "https://the-decoder.com/",
        "feed_url": "https://the-decoder.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["ai", "machine-learning", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "AI News",
        "homepage_url": "https://www.artificialintelligence-news.com/",
        "feed_url": "https://www.artificialintelligence-news.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["ai", "machine-learning", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Synced",
        "homepage_url": "https://syncedreview.com/",
        "feed_url": "https://syncedreview.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["ai", "machine-learning", "research"],
        "bot_sensitivity": 1,
    },
    # --- Gaming industry ---
    {
        "name": "GamesIndustry.biz",
        "homepage_url": "https://www.gamesindustry.biz/",
        "feed_url": "https://www.gamesindustry.biz/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["gaming", "business", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Game Developer",
        "homepage_url": "https://www.gamedeveloper.com/",
        "feed_url": "https://www.gamedeveloper.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["gaming", "game-dev", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "80 Level",
        "homepage_url": "https://80.lv/",
        "feed_url": "https://80.lv/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["gaming", "game-dev", "art"],
        "bot_sensitivity": 1,
    },
    {
        "name": "PocketGamer.biz",
        "homepage_url": "https://www.pocketgamer.biz/",
        "feed_url": "https://www.pocketgamer.biz/rss/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["gaming", "mobile", "business"],
        "bot_sensitivity": 1,
    },
    # --- Fintech / banking ---
    {
        "name": "Finextra",
        "homepage_url": "https://www.finextra.com/",
        "feed_url": "https://www.finextra.com/rss/headlines.aspx",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["fintech", "banking", "finance"],
        "bot_sensitivity": 1,
    },
    {
        "name": "PYMNTS",
        "homepage_url": "https://www.pymnts.com/",
        "feed_url": "https://www.pymnts.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["fintech", "payments", "finance"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Banking Dive",
        "homepage_url": "https://www.bankingdive.com/",
        "feed_url": "https://www.bankingdive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["banking", "fintech", "finance"],
        "bot_sensitivity": 1,
    },
    {
        "name": "BanklessTimes",
        "homepage_url": "https://www.banklesstimes.com/",
        "feed_url": "https://www.banklesstimes.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["fintech", "crypto", "finance"],
        "bot_sensitivity": 1,
    },
    {
        "name": "finews.com",
        "homepage_url": "https://www.finews.com/",
        "feed_url": "https://www.finews.com/news?format=feed&type=rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "CH",
        "languages": ["en"],
        "categories": ["banking", "finance", "wealth-management"],
        "bot_sensitivity": 1,
    },
    {
        "name": "TechCrunch Fintech",
        "homepage_url": "https://techcrunch.com/category/fintech/",
        "feed_url": "https://techcrunch.com/category/fintech/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["fintech", "startups", "finance"],
        "bot_sensitivity": 1,
    },
    # --- Retail / supply chain / food trade ---
    {
        "name": "Retail Dive",
        "homepage_url": "https://www.retaildive.com/",
        "feed_url": "https://www.retaildive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["retail", "business", "ecommerce"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Supply Chain Dive",
        "homepage_url": "https://www.supplychaindive.com/",
        "feed_url": "https://www.supplychaindive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["supply-chain", "logistics", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Food Dive",
        "homepage_url": "https://www.fooddive.com/",
        "feed_url": "https://www.fooddive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["food", "manufacturing", "business"],
        "bot_sensitivity": 1,
    },
    # --- Healthcare IT / pharma / biotech ---
    {
        "name": "Fierce Healthcare",
        "homepage_url": "https://www.fiercehealthcare.com/",
        "feed_url": "https://www.fiercehealthcare.com/rss/xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["healthcare", "health-it", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "MobiHealthNews",
        "homepage_url": "https://www.mobihealthnews.com/",
        "feed_url": "https://www.mobihealthnews.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["health-it", "digital-health", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Healthcare Dive",
        "homepage_url": "https://www.healthcaredive.com/",
        "feed_url": "https://www.healthcaredive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["healthcare", "business", "health-it"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Fierce Pharma",
        "homepage_url": "https://www.fiercepharma.com/",
        "feed_url": "https://www.fiercepharma.com/rss/xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["pharma", "healthcare", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Fierce Biotech",
        "homepage_url": "https://www.fiercebiotech.com/",
        "feed_url": "https://www.fiercebiotech.com/rss/xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["biotech", "healthcare", "research"],
        "bot_sensitivity": 1,
    },
    # --- Manufacturing / robotics / automation ---
    {
        "name": "Manufacturing Dive",
        "homepage_url": "https://www.manufacturingdive.com/",
        "feed_url": "https://www.manufacturingdive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["manufacturing", "industry", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Robot Report",
        "homepage_url": "https://www.therobotreport.com/",
        "feed_url": "https://www.therobotreport.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["robotics", "automation", "manufacturing"],
        "bot_sensitivity": 1,
    },
    {
        "name": "RoboticsTomorrow",
        "homepage_url": "https://www.roboticstomorrow.com/",
        "feed_url": "https://www.roboticstomorrow.com/rss/news.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["robotics", "automation", "manufacturing"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Design News",
        "homepage_url": "https://www.designnews.com/",
        "feed_url": "https://www.designnews.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["engineering", "manufacturing", "design"],
        "bot_sensitivity": 1,
    },
    # --- EVs / batteries / energy storage ---
    {
        "name": "Electrek",
        "homepage_url": "https://electrek.co/",
        "feed_url": "https://electrek.co/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["ev", "clean-energy", "transport"],
        "bot_sensitivity": 1,
    },
    {
        "name": "InsideEVs",
        "homepage_url": "https://insideevs.com/",
        "feed_url": "https://insideevs.com/rss/articles/all/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["ev", "automotive", "transport"],
        "bot_sensitivity": 1,
    },
    {
        "name": "CleanTechnica",
        "homepage_url": "https://cleantechnica.com/",
        "feed_url": "https://cleantechnica.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["clean-energy", "ev", "sustainability"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Energy-Storage.news",
        "homepage_url": "https://www.energy-storage.news/",
        "feed_url": "https://www.energy-storage.news/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["energy-storage", "batteries", "clean-energy"],
        "bot_sensitivity": 1,
    },
    # --- Solar / wind / nuclear / hydrogen / utilities ---
    {
        "name": "PV Magazine",
        "homepage_url": "https://www.pv-magazine.com/",
        "feed_url": "https://www.pv-magazine.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["solar", "clean-energy", "renewables"],
        "bot_sensitivity": 1,
    },
    {
        "name": "PV Tech",
        "homepage_url": "https://www.pv-tech.org/",
        "feed_url": "https://www.pv-tech.org/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["solar", "renewables", "clean-energy"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Windpower Monthly",
        "homepage_url": "https://www.windpowermonthly.com/",
        "feed_url": "https://www.windpowermonthly.com/rss/news",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["wind", "renewables", "clean-energy"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Offshore Wind",
        "homepage_url": "https://www.offshorewind.biz/",
        "feed_url": "https://www.offshorewind.biz/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["wind", "offshore", "renewables"],
        "bot_sensitivity": 1,
    },
    {
        "name": "World Nuclear News",
        "homepage_url": "https://www.world-nuclear-news.org/",
        "feed_url": "https://www.world-nuclear-news.org/rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["nuclear", "energy", "power"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Hydrogen Central",
        "homepage_url": "https://hydrogen-central.com/",
        "feed_url": "https://hydrogen-central.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["hydrogen", "clean-energy", "renewables"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Power Technology",
        "homepage_url": "https://www.power-technology.com/",
        "feed_url": "https://www.power-technology.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["power", "energy", "utilities"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Utility Dive",
        "homepage_url": "https://www.utilitydive.com/",
        "feed_url": "https://www.utilitydive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["utilities", "energy", "power"],
        "bot_sensitivity": 1,
    },
    # --- Water / construction / smart cities ---
    {
        "name": "Smart Water Magazine",
        "homepage_url": "https://www.smartwatermagazine.com/",
        "feed_url": "https://www.smartwatermagazine.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["water", "utilities", "environment"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Construction Dive",
        "homepage_url": "https://www.constructiondive.com/",
        "feed_url": "https://www.constructiondive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["construction", "infrastructure", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Smart Cities Dive",
        "homepage_url": "https://www.smartcitiesdive.com/",
        "feed_url": "https://www.smartcitiesdive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["smart-cities", "infrastructure", "technology"],
        "bot_sensitivity": 1,
    },
    # --- Chemicals / packaging / textiles / plastics ---
    {
        "name": "Chemical Engineering",
        "homepage_url": "https://www.chemengonline.com/",
        "feed_url": "https://www.chemengonline.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["chemicals", "engineering", "manufacturing"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Packaging Gateway",
        "homepage_url": "https://www.packaging-gateway.com/",
        "feed_url": "https://www.packaging-gateway.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["packaging", "manufacturing", "industry"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Packaging News",
        "homepage_url": "https://www.packagingnews.co.uk/",
        "feed_url": "https://www.packagingnews.co.uk/feed",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GB",
        "languages": ["en"],
        "categories": ["packaging", "manufacturing", "industry"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Just Style",
        "homepage_url": "https://www.just-style.com/",
        "feed_url": "https://www.just-style.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["textiles", "apparel", "manufacturing"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Textile World",
        "homepage_url": "https://www.textileworld.com/",
        "feed_url": "https://www.textileworld.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["textiles", "manufacturing", "industry"],
        "bot_sensitivity": 1,
    },
    {
        "name": "PlasticsToday",
        "homepage_url": "https://www.plasticstoday.com/",
        "feed_url": "https://www.plasticstoday.com/rss.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["plastics", "manufacturing", "materials"],
        "bot_sensitivity": 1,
    },
    # --- Semiconductors / electronics engineering ---
    {
        "name": "Semiconductor Engineering",
        "homepage_url": "https://semiengineering.com/",
        "feed_url": "https://semiengineering.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["semiconductors", "chip-design", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "Semiconductor Digest",
        "homepage_url": "https://www.semiconductor-digest.com/",
        "feed_url": "https://www.semiconductor-digest.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["semiconductors", "manufacturing", "technology"],
        "bot_sensitivity": 1,
    },
    {
        "name": "EE Times",
        "homepage_url": "https://www.eetimes.com/",
        "feed_url": "https://www.eetimes.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["electronics", "semiconductors", "engineering"],
        "bot_sensitivity": 1,
    },
    {
        "name": "IEEE Spectrum",
        "homepage_url": "https://spectrum.ieee.org/",
        "feed_url": "https://spectrum.ieee.org/feeds/feed.rss",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["engineering", "technology", "research"],
        "bot_sensitivity": 1,
    },
    # --- Cybersecurity / enterprise IT ---
    {
        "name": "Cybersecurity Dive",
        "homepage_url": "https://www.cybersecuritydive.com/",
        "feed_url": "https://www.cybersecuritydive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["cybersecurity", "enterprise-it", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "BleepingComputer",
        "homepage_url": "https://www.bleepingcomputer.com/",
        "feed_url": "https://www.bleepingcomputer.com/feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["cybersecurity", "technology", "software"],
        "bot_sensitivity": 1,
    },
    {
        "name": "CIO Dive",
        "homepage_url": "https://www.ciodive.com/",
        "feed_url": "https://www.ciodive.com/feeds/news/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "US",
        "languages": ["en"],
        "categories": ["enterprise-it", "cio", "business"],
        "bot_sensitivity": 1,
    },
    {
        "name": "The Register",
        "homepage_url": "https://www.theregister.com/",
        "feed_url": "https://www.theregister.com/headlines.atom",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["enterprise-it", "technology", "software"],
        "bot_sensitivity": 1,
    },
    {
        "name": "ITPro",
        "homepage_url": "https://www.itpro.com/",
        "feed_url": "https://www.itpro.com/feeds.xml",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GB",
        "languages": ["en"],
        "categories": ["enterprise-it", "technology", "business"],
        "bot_sensitivity": 1,
    },
    # --- Applied tech / science engineering ---
    {
        "name": "Tech Xplore",
        "homepage_url": "https://techxplore.com/",
        "feed_url": "https://techxplore.com/rss-feed/",
        "api_kind": None,
        "fetch_method": "rss",
        "region": "GLOBAL",
        "languages": ["en"],
        "categories": ["technology", "engineering", "research"],
        "bot_sensitivity": 1,
    },
]
