"""Extra seed bucket — US LOCAL / REGIONAL depth.

Hand-curated, individually live-verified feeds for the long tail of US local and
regional journalism: state & metro daily newspapers, the Advance Local
(Newhouse) regional dailies, NPR / public-radio member stations, the
nonprofit "States Newsroom" statehouse network and other independent local
newsrooms, plus a spread of alt-weeklies. National flagships (NYT, WaPo, WSJ,
USA Today, AP) are assumed already covered elsewhere and are intentionally
omitted; the focus here is metro / state / city-level outlets and language- and
community-specific desks.

Every ``rss`` entry below was fetched with a desktop browser User-Agent on
2026-06-03 and confirmed to return a parseable feed (<rss/<feed/<rdf) with at
least one real <item/<entry. Outlets whose feeds 404'd, 403'd, or returned
HTML-only on that date were discarded (notable dead ones: the entire Gannett
``/feeds/rss/news`` network — Arizona Republic, Tennessean, Detroit Free Press,
Courier-Journal, Milwaukee Journal Sentinel; the Tribune Publishing
``arc/outboundfeeds`` set — Chicago Tribune, Baltimore Sun, Orlando Sentinel,
Hartford Courant, NY Daily News; the McClatchy dailies — Miami Herald,
Sacramento Bee, Kansas City Star; SF Chronicle / Hearst; and the MediaNews
Group So-Cal & Bay-Area chain — Mercury News, OC Register, Denver Post, Daily
News). NPR member-station feed paths vary wildly per station (no single
convention works), so each surviving station path below was probed individually.

Shape matches ``newskoo.sources.schemas.SourceCreate``: name, homepage_url,
feed_url, api_kind, fetch_method, region, languages, categories, bot_sensitivity.
"""

from __future__ import annotations

SOURCES: list[dict] = [
    # ── Metro & state daily newspapers ───────────────────────────────────────
    {"name": "The Boston Globe (Big Picture)", "homepage_url": "https://www.bostonglobe.com/", "feed_url": "https://www.bostonglobe.com/rss/bigpicture", "api_kind": None, "fetch_method": "rss", "region": "US-MA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Star Tribune (Minneapolis)", "homepage_url": "https://www.startribune.com/", "feed_url": "https://www.startribune.com/rss/", "api_kind": None, "fetch_method": "rss", "region": "US-MN", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Seattle Times", "homepage_url": "https://www.seattletimes.com/", "feed_url": "https://www.seattletimes.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-WA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Los Angeles Times (Local)", "homepage_url": "https://www.latimes.com/local", "feed_url": "https://www.latimes.com/local/rss2.0.xml", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Los Angeles Times (California)", "homepage_url": "https://www.latimes.com/california", "feed_url": "https://www.latimes.com/california/rss2.0.xml", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "New York Post", "homepage_url": "https://nypost.com/", "feed_url": "https://nypost.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NY", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Chicago Sun-Times", "homepage_url": "https://chicago.suntimes.com/", "feed_url": "https://chicago.suntimes.com/rss/index.xml", "api_kind": None, "fetch_method": "rss", "region": "US-IL", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Spokesman-Review (Spokane)", "homepage_url": "https://www.spokesman.com/", "feed_url": "https://www.spokesman.com/feeds/stories/", "api_kind": None, "fetch_method": "rss", "region": "US-WA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},

    # ── Advance Local (Newhouse) regional dailies ────────────────────────────
    {"name": "The Oregonian / OregonLive", "homepage_url": "https://www.oregonlive.com/", "feed_url": "https://www.oregonlive.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-OR", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "NJ.com (Star-Ledger)", "homepage_url": "https://www.nj.com/", "feed_url": "https://nj.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-NJ", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Cleveland.com (The Plain Dealer)", "homepage_url": "https://www.cleveland.com/", "feed_url": "https://www.cleveland.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-OH", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "AL.com (Alabama)", "homepage_url": "https://www.al.com/", "feed_url": "https://www.al.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-AL", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "MLive (Michigan)", "homepage_url": "https://www.mlive.com/", "feed_url": "https://www.mlive.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-MI", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "MassLive (Massachusetts)", "homepage_url": "https://www.masslive.com/", "feed_url": "https://www.masslive.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-MA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "PennLive (Patriot-News)", "homepage_url": "https://www.pennlive.com/", "feed_url": "https://www.pennlive.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-PA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Syracuse.com (Post-Standard)", "homepage_url": "https://www.syracuse.com/", "feed_url": "https://www.syracuse.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-NY", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "NOLA.com (The Times-Picayune | Advocate)", "homepage_url": "https://www.nola.com/", "feed_url": "https://www.nola.com/search/?f=rss", "api_kind": None, "fetch_method": "rss", "region": "US-LA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Gulflive (Mississippi Gulf Coast)", "homepage_url": "https://www.gulflive.com/", "feed_url": "https://www.gulflive.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-MS", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "LehighValleyLive (Express-Times)", "homepage_url": "https://www.lehighvalleylive.com/", "feed_url": "https://www.lehighvalleylive.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-PA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "SILive (Staten Island Advance)", "homepage_url": "https://www.silive.com/", "feed_url": "https://www.silive.com/arc/outboundfeeds/rss/?outputType=xml", "api_kind": None, "fetch_method": "rss", "region": "US-NY", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},

    # ── NPR / public-radio member stations ───────────────────────────────────
    {"name": "WBUR (Boston)", "homepage_url": "https://www.wbur.org/", "feed_url": "https://www.wbur.org/feed", "api_kind": None, "fetch_method": "rss", "region": "US-MA", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "WBEZ (Chicago)", "homepage_url": "https://www.wbez.org/", "feed_url": "https://www.wbez.org/rss", "api_kind": None, "fetch_method": "rss", "region": "US-IL", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "WAMU (Washington DC)", "homepage_url": "https://www.wamu.org/", "feed_url": "https://www.wamu.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-DC", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "Gothamist (New York)", "homepage_url": "https://gothamist.com/", "feed_url": "https://gothamist.com/feed", "api_kind": None, "fetch_method": "rss", "region": "US-NY", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "LAist (Southern California)", "homepage_url": "https://laist.com/", "feed_url": "https://laist.com/index.rss", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "KPBS (San Diego)", "homepage_url": "https://www.kpbs.org/", "feed_url": "https://www.kpbs.org/index.rss", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "KUT (Austin)", "homepage_url": "https://www.kut.org/", "feed_url": "https://www.kut.org/feeds/all.rss", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "Texas Public Radio (San Antonio)", "homepage_url": "https://www.tpr.org/", "feed_url": "https://www.tpr.org/feeds/all.rss", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "KERA News (Dallas-Fort Worth)", "homepage_url": "https://www.kera.org/", "feed_url": "https://www.kera.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "Houston Public Media", "homepage_url": "https://www.houstonpublicmedia.org/", "feed_url": "https://www.houstonpublicmedia.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},
    {"name": "Colorado Public Radio", "homepage_url": "https://www.cpr.org/", "feed_url": "https://www.cpr.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-CO", "languages": ["en"], "categories": ["local", "public-radio", "news"], "bot_sensitivity": 1},

    # ── States Newsroom & nonprofit statehouse outlets ───────────────────────
    {"name": "Texas Tribune", "homepage_url": "https://www.texastribune.org/", "feed_url": "https://www.texastribune.org/feeds/main/", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "CalMatters", "homepage_url": "https://calmatters.org/", "feed_url": "https://calmatters.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "The Texas Observer", "homepage_url": "https://www.texasobserver.org/", "feed_url": "https://www.texasobserver.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Florida Phoenix", "homepage_url": "https://floridaphoenix.com/", "feed_url": "https://floridaphoenix.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-FL", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Georgia Recorder", "homepage_url": "https://georgiarecorder.com/", "feed_url": "https://georgiarecorder.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-GA", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Colorado Newsline", "homepage_url": "https://coloradonewsline.com/", "feed_url": "https://www.coloradonewsline.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-CO", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Ohio Capital Journal", "homepage_url": "https://ohiocapitaljournal.com/", "feed_url": "https://ohiocapitaljournal.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-OH", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Michigan Advance", "homepage_url": "https://michiganadvance.com/", "feed_url": "https://michiganadvance.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-MI", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Virginia Mercury", "homepage_url": "https://www.virginiamercury.com/", "feed_url": "https://www.virginiamercury.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-VA", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Missouri Independent", "homepage_url": "https://missouriindependent.com/", "feed_url": "https://missouriindependent.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-MO", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Nevada Current", "homepage_url": "https://nevadacurrent.com/", "feed_url": "https://www.nevadacurrent.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NV", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "New Jersey Monitor", "homepage_url": "https://newjerseymonitor.com/", "feed_url": "https://newjerseymonitor.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NJ", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "North Carolina Health News", "homepage_url": "https://www.northcarolinahealthnews.org/", "feed_url": "https://www.northcarolinahealthnews.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NC", "languages": ["en"], "categories": ["local", "health", "news"], "bot_sensitivity": 1},
    {"name": "NC Newsline", "homepage_url": "https://ncnewsline.com/", "feed_url": "https://ncnewsline.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NC", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Wisconsin Examiner", "homepage_url": "https://wisconsinexaminer.com/", "feed_url": "https://wisconsinexaminer.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-WI", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Minnesota Reformer", "homepage_url": "https://minnesotareformer.com/", "feed_url": "https://www.minnesotareformer.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-MN", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Oklahoma Voice", "homepage_url": "https://oklahomavoice.com/", "feed_url": "https://oklahomavoice.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-OK", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Kansas Reflector", "homepage_url": "https://kansasreflector.com/", "feed_url": "https://kansasreflector.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-KS", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Nebraska Examiner", "homepage_url": "https://nebraskaexaminer.com/", "feed_url": "https://nebraskaexaminer.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NE", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Iowa Capital Dispatch", "homepage_url": "https://iowacapitaldispatch.com/", "feed_url": "https://iowacapitaldispatch.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-IA", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Idaho Capital Sun", "homepage_url": "https://idahocapitalsun.com/", "feed_url": "https://idahocapitalsun.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-ID", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "WyoFile (Wyoming)", "homepage_url": "https://www.wyofile.com/", "feed_url": "https://www.wyofile.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-WY", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Source New Mexico", "homepage_url": "https://sourcenm.com/", "feed_url": "https://sourcenm.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NM", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Arizona Mirror", "homepage_url": "https://azmirror.com/", "feed_url": "https://azmirror.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-AZ", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Oregon Capital Chronicle", "homepage_url": "https://oregoncapitalchronicle.com/", "feed_url": "https://oregoncapitalchronicle.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-OR", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Alabama Reflector", "homepage_url": "https://alabamareflector.com/", "feed_url": "https://alabamareflector.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-AL", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Tennessee Lookout", "homepage_url": "https://tennesseelookout.com/", "feed_url": "https://www.tennesseelookout.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-TN", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Mississippi Today", "homepage_url": "https://mississippitoday.org/", "feed_url": "https://mississippitoday.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-MS", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "SC Daily Gazette (South Carolina)", "homepage_url": "https://scdailygazette.com/", "feed_url": "https://scdailygazette.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-SC", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "New Hampshire Bulletin", "homepage_url": "https://newhampshirebulletin.com/", "feed_url": "https://newhampshirebulletin.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-NH", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "The Maine Monitor", "homepage_url": "https://www.themainemonitor.org/", "feed_url": "https://www.themainemonitor.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-ME", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "VTDigger (Vermont)", "homepage_url": "https://vtdigger.org/", "feed_url": "https://vtdigger.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-VT", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "West Virginia Watch", "homepage_url": "https://westvirginiawatch.com/", "feed_url": "https://westvirginiawatch.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-WV", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Maryland Matters", "homepage_url": "https://marylandmatters.org/", "feed_url": "https://marylandmatters.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-MD", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Daily Montanan", "homepage_url": "https://dailymontanan.com/", "feed_url": "https://dailymontanan.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-MT", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Alaska Beacon", "homepage_url": "https://alaskabeacon.com/", "feed_url": "https://alaskabeacon.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-AK", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},
    {"name": "Utah News Dispatch", "homepage_url": "https://utahnewsdispatch.com/", "feed_url": "https://utahnewsdispatch.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-UT", "languages": ["en"], "categories": ["local", "politics", "news"], "bot_sensitivity": 1},

    # ── Independent / nonprofit local newsrooms ──────────────────────────────
    {"name": "Honolulu Civil Beat", "homepage_url": "https://www.civilbeat.org/", "feed_url": "https://www.civilbeat.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-HI", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The Colorado Sun", "homepage_url": "https://coloradosun.com/", "feed_url": "https://coloradosun.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-CO", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "MinnPost (Minnesota)", "homepage_url": "https://www.minnpost.com/", "feed_url": "https://www.minnpost.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-MN", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Voice of San Diego", "homepage_url": "https://voiceofsandiego.org/", "feed_url": "https://www.voiceofsandiego.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Mission Local (San Francisco)", "homepage_url": "https://missionlocal.org/", "feed_url": "https://missionlocal.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Berkeleyside", "homepage_url": "https://www.berkeleyside.org/", "feed_url": "https://www.berkeleyside.org/feed", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "The City (NYC)", "homepage_url": "https://www.thecity.nyc/", "feed_url": "https://www.thecity.nyc/rss/", "api_kind": None, "fetch_method": "rss", "region": "US-NY", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Block Club Chicago", "homepage_url": "https://blockclubchicago.org/", "feed_url": "https://blockclubchicago.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-IL", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},
    {"name": "Austin Monitor", "homepage_url": "https://www.austinmonitor.com/", "feed_url": "https://www.austinmonitor.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "news"], "bot_sensitivity": 1},

    # ── Alt-weeklies (city culture/news) ─────────────────────────────────────
    {"name": "Chicago Reader", "homepage_url": "https://chicagoreader.com/", "feed_url": "https://www.chicagoreader.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-IL", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Dallas Observer", "homepage_url": "https://www.dallasobserver.com/", "feed_url": "https://www.dallasobserver.com/rss", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Houston Press", "homepage_url": "https://www.houstonpress.com/", "feed_url": "https://www.houstonpress.com/rss", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Westword (Denver)", "homepage_url": "https://www.westword.com/", "feed_url": "https://www.westword.com/rss", "api_kind": None, "fetch_method": "rss", "region": "US-CO", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Miami New Times", "homepage_url": "https://www.miaminewtimes.com/", "feed_url": "https://www.miaminewtimes.com/rss", "api_kind": None, "fetch_method": "rss", "region": "US-FL", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Phoenix New Times", "homepage_url": "https://www.phoenixnewtimes.com/", "feed_url": "https://www.phoenixnewtimes.com/rss", "api_kind": None, "fetch_method": "rss", "region": "US-AZ", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Detroit Metro Times", "homepage_url": "https://www.metrotimes.com/", "feed_url": "https://www.metrotimes.com/detroit/Rss.xml", "api_kind": None, "fetch_method": "rss", "region": "US-MI", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Cleveland Scene", "homepage_url": "https://www.clevescene.com/", "feed_url": "https://www.clevescene.com/cleveland/Rss.xml", "api_kind": None, "fetch_method": "rss", "region": "US-OH", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Seven Days (Vermont)", "homepage_url": "https://www.sevendaysvt.com/", "feed_url": "https://www.sevendaysvt.com/vermont/Rss.xml", "api_kind": None, "fetch_method": "rss", "region": "US-VT", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "The Stranger (Seattle)", "homepage_url": "https://www.thestranger.com/", "feed_url": "https://www.thestranger.com/seattle/Rss.xml", "api_kind": None, "fetch_method": "rss", "region": "US-WA", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "East Bay Express (Oakland)", "homepage_url": "https://eastbayexpress.com/", "feed_url": "https://www.eastbayexpress.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-CA", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Dallas Voice", "homepage_url": "https://dallasvoice.com/", "feed_url": "https://www.dallasvoice.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-TX", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},
    {"name": "Philadelphia Weekly", "homepage_url": "https://www.philadelphiaweekly.com/", "feed_url": "https://www.philadelphiaweekly.com/feed/", "api_kind": None, "fetch_method": "rss", "region": "US-PA", "languages": ["en"], "categories": ["local", "alt-weekly", "culture"], "bot_sensitivity": 1},

    # ── National-reach investigative / accountability (US-focused) ────────────
    {"name": "ProPublica", "homepage_url": "https://www.propublica.org/", "feed_url": "https://www.propublica.org/feeds/propublica/main", "api_kind": None, "fetch_method": "rss", "region": "US", "languages": ["en"], "categories": ["investigative", "news"], "bot_sensitivity": 1},
    {"name": "The Marshall Project", "homepage_url": "https://www.themarshallproject.org/", "feed_url": "https://www.themarshallproject.org/rss/recent.rss", "api_kind": None, "fetch_method": "rss", "region": "US", "languages": ["en"], "categories": ["investigative", "criminal-justice", "news"], "bot_sensitivity": 1},
    {"name": "Grist (climate/environment)", "homepage_url": "https://grist.org/", "feed_url": "https://grist.org/feed/", "api_kind": None, "fetch_method": "rss", "region": "US", "languages": ["en"], "categories": ["climate", "environment", "news"], "bot_sensitivity": 1},
]
